package com.rawabi.model;

// Generated Jul 24, 2012 12:30:09 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

/**
 * AccountActivity generated by hbm2java
 */
public class AccountActivity implements java.io.Serializable {

	private String activityId;
	private Subscriber subscriber;
	private ServiceProvider serviceProvider;
	private ProductOffering productOffering;
	private BigDecimal eventTypeId;
	private BigDecimal totalAmount;
	private BigDecimal currencyId;
	private String eventId;
	private char reversableFlag;
	private BigDecimal serviceId;
	private Date timeDateStamp;
	private BigDecimal eventAmount;
	private String origNbr;
	private String destNbr;
	private BigDecimal duration;
	private BigDecimal reversedActivityId;
	private Character removeFlag;
	private BigDecimal rateId1;
	private BigDecimal rateAmt1;
	private BigDecimal rateId2;
	private BigDecimal rateAmt2;
	private BigDecimal rateId3;
	private BigDecimal rateAmt3;
	private BigDecimal rateId4;
	private BigDecimal rateAmt4;
	private BigDecimal rateId5;
	private BigDecimal rateAmt5;
	private BigDecimal rateId6;
	private BigDecimal rateAmt6;
	private BigDecimal rateId7;
	private BigDecimal rateAmt7;
	private BigDecimal rateId8;
	private BigDecimal rateAmt8;
	private BigDecimal rateId9;
	private BigDecimal rateAmt9;
	private BigDecimal rateId10;
	private BigDecimal rateAmt10;
	private BigDecimal rateId11;
	private BigDecimal rateAmt11;
	private BigDecimal rateId12;
	private BigDecimal rateAmt12;
	private BigDecimal callConnectionFee;
	private BigDecimal tier1Amt;
	private BigDecimal tier2Amt;
	private BigDecimal tier3Amt;
	private BigDecimal totalBongAmt;
	private BigDecimal custRateId1;
	private BigDecimal custRateId2;
	private BigDecimal custRateId3;
	private BigDecimal custRateId4;
	private BigDecimal custRateAmt1;
	private BigDecimal custRateAmt2;
	private BigDecimal custRateAmt3;
	private BigDecimal custRateAmt4;

	public AccountActivity() {
	}

	public AccountActivity(String activityId, Subscriber subscriber,
			ServiceProvider serviceProvider, BigDecimal eventTypeId,
			BigDecimal totalAmount, BigDecimal currencyId, String eventId,
			char reversableFlag) {
		this.activityId = activityId;
		this.subscriber = subscriber;
		this.serviceProvider = serviceProvider;
		this.eventTypeId = eventTypeId;
		this.totalAmount = totalAmount;
		this.currencyId = currencyId;
		this.eventId = eventId;
		this.reversableFlag = reversableFlag;
	}

	public AccountActivity(String activityId, Subscriber subscriber,
			ServiceProvider serviceProvider, ProductOffering productOffering,
			BigDecimal eventTypeId, BigDecimal totalAmount,
			BigDecimal currencyId, String eventId, char reversableFlag,
			BigDecimal serviceId, Date timeDateStamp, BigDecimal eventAmount,
			String origNbr, String destNbr, BigDecimal duration,
			BigDecimal reversedActivityId, Character removeFlag,
			BigDecimal rateId1, BigDecimal rateAmt1, BigDecimal rateId2,
			BigDecimal rateAmt2, BigDecimal rateId3, BigDecimal rateAmt3,
			BigDecimal rateId4, BigDecimal rateAmt4, BigDecimal rateId5,
			BigDecimal rateAmt5, BigDecimal rateId6, BigDecimal rateAmt6,
			BigDecimal rateId7, BigDecimal rateAmt7, BigDecimal rateId8,
			BigDecimal rateAmt8, BigDecimal rateId9, BigDecimal rateAmt9,
			BigDecimal rateId10, BigDecimal rateAmt10, BigDecimal rateId11,
			BigDecimal rateAmt11, BigDecimal rateId12, BigDecimal rateAmt12,
			BigDecimal callConnectionFee, BigDecimal tier1Amt,
			BigDecimal tier2Amt, BigDecimal tier3Amt, BigDecimal totalBongAmt,
			BigDecimal custRateId1, BigDecimal custRateId2,
			BigDecimal custRateId3, BigDecimal custRateId4,
			BigDecimal custRateAmt1, BigDecimal custRateAmt2,
			BigDecimal custRateAmt3, BigDecimal custRateAmt4) {
		this.activityId = activityId;
		this.subscriber = subscriber;
		this.serviceProvider = serviceProvider;
		this.productOffering = productOffering;
		this.eventTypeId = eventTypeId;
		this.totalAmount = totalAmount;
		this.currencyId = currencyId;
		this.eventId = eventId;
		this.reversableFlag = reversableFlag;
		this.serviceId = serviceId;
		this.timeDateStamp = timeDateStamp;
		this.eventAmount = eventAmount;
		this.origNbr = origNbr;
		this.destNbr = destNbr;
		this.duration = duration;
		this.reversedActivityId = reversedActivityId;
		this.removeFlag = removeFlag;
		this.rateId1 = rateId1;
		this.rateAmt1 = rateAmt1;
		this.rateId2 = rateId2;
		this.rateAmt2 = rateAmt2;
		this.rateId3 = rateId3;
		this.rateAmt3 = rateAmt3;
		this.rateId4 = rateId4;
		this.rateAmt4 = rateAmt4;
		this.rateId5 = rateId5;
		this.rateAmt5 = rateAmt5;
		this.rateId6 = rateId6;
		this.rateAmt6 = rateAmt6;
		this.rateId7 = rateId7;
		this.rateAmt7 = rateAmt7;
		this.rateId8 = rateId8;
		this.rateAmt8 = rateAmt8;
		this.rateId9 = rateId9;
		this.rateAmt9 = rateAmt9;
		this.rateId10 = rateId10;
		this.rateAmt10 = rateAmt10;
		this.rateId11 = rateId11;
		this.rateAmt11 = rateAmt11;
		this.rateId12 = rateId12;
		this.rateAmt12 = rateAmt12;
		this.callConnectionFee = callConnectionFee;
		this.tier1Amt = tier1Amt;
		this.tier2Amt = tier2Amt;
		this.tier3Amt = tier3Amt;
		this.totalBongAmt = totalBongAmt;
		this.custRateId1 = custRateId1;
		this.custRateId2 = custRateId2;
		this.custRateId3 = custRateId3;
		this.custRateId4 = custRateId4;
		this.custRateAmt1 = custRateAmt1;
		this.custRateAmt2 = custRateAmt2;
		this.custRateAmt3 = custRateAmt3;
		this.custRateAmt4 = custRateAmt4;
	}

	public String getActivityId() {
		return this.activityId;
	}

	public void setActivityId(String activityId) {
		this.activityId = activityId;
	}

	public Subscriber getSubscriber() {
		return this.subscriber;
	}

	public void setSubscriber(Subscriber subscriber) {
		this.subscriber = subscriber;
	}

	public ServiceProvider getServiceProvider() {
		return this.serviceProvider;
	}

	public void setServiceProvider(ServiceProvider serviceProvider) {
		this.serviceProvider = serviceProvider;
	}

	public ProductOffering getProductOffering() {
		return this.productOffering;
	}

	public void setProductOffering(ProductOffering productOffering) {
		this.productOffering = productOffering;
	}

	public BigDecimal getEventTypeId() {
		return this.eventTypeId;
	}

	public void setEventTypeId(BigDecimal eventTypeId) {
		this.eventTypeId = eventTypeId;
	}

	public BigDecimal getTotalAmount() {
		return this.totalAmount;
	}

	public void setTotalAmount(BigDecimal totalAmount) {
		this.totalAmount = totalAmount;
	}

	public BigDecimal getCurrencyId() {
		return this.currencyId;
	}

	public void setCurrencyId(BigDecimal currencyId) {
		this.currencyId = currencyId;
	}

	public String getEventId() {
		return this.eventId;
	}

	public void setEventId(String eventId) {
		this.eventId = eventId;
	}

	public char getReversableFlag() {
		return this.reversableFlag;
	}

	public void setReversableFlag(char reversableFlag) {
		this.reversableFlag = reversableFlag;
	}

	public BigDecimal getServiceId() {
		return this.serviceId;
	}

	public void setServiceId(BigDecimal serviceId) {
		this.serviceId = serviceId;
	}

	public Date getTimeDateStamp() {
		return this.timeDateStamp;
	}

	public void setTimeDateStamp(Date timeDateStamp) {
		this.timeDateStamp = timeDateStamp;
	}

	public BigDecimal getEventAmount() {
		return this.eventAmount;
	}

	public void setEventAmount(BigDecimal eventAmount) {
		this.eventAmount = eventAmount;
	}

	public String getOrigNbr() {
		return this.origNbr;
	}

	public void setOrigNbr(String origNbr) {
		this.origNbr = origNbr;
	}

	public String getDestNbr() {
		return this.destNbr;
	}

	public void setDestNbr(String destNbr) {
		this.destNbr = destNbr;
	}

	public BigDecimal getDuration() {
		return this.duration;
	}

	public void setDuration(BigDecimal duration) {
		this.duration = duration;
	}

	public BigDecimal getReversedActivityId() {
		return this.reversedActivityId;
	}

	public void setReversedActivityId(BigDecimal reversedActivityId) {
		this.reversedActivityId = reversedActivityId;
	}

	public Character getRemoveFlag() {
		return this.removeFlag;
	}

	public void setRemoveFlag(Character removeFlag) {
		this.removeFlag = removeFlag;
	}

	public BigDecimal getRateId1() {
		return this.rateId1;
	}

	public void setRateId1(BigDecimal rateId1) {
		this.rateId1 = rateId1;
	}

	public BigDecimal getRateAmt1() {
		return this.rateAmt1;
	}

	public void setRateAmt1(BigDecimal rateAmt1) {
		this.rateAmt1 = rateAmt1;
	}

	public BigDecimal getRateId2() {
		return this.rateId2;
	}

	public void setRateId2(BigDecimal rateId2) {
		this.rateId2 = rateId2;
	}

	public BigDecimal getRateAmt2() {
		return this.rateAmt2;
	}

	public void setRateAmt2(BigDecimal rateAmt2) {
		this.rateAmt2 = rateAmt2;
	}

	public BigDecimal getRateId3() {
		return this.rateId3;
	}

	public void setRateId3(BigDecimal rateId3) {
		this.rateId3 = rateId3;
	}

	public BigDecimal getRateAmt3() {
		return this.rateAmt3;
	}

	public void setRateAmt3(BigDecimal rateAmt3) {
		this.rateAmt3 = rateAmt3;
	}

	public BigDecimal getRateId4() {
		return this.rateId4;
	}

	public void setRateId4(BigDecimal rateId4) {
		this.rateId4 = rateId4;
	}

	public BigDecimal getRateAmt4() {
		return this.rateAmt4;
	}

	public void setRateAmt4(BigDecimal rateAmt4) {
		this.rateAmt4 = rateAmt4;
	}

	public BigDecimal getRateId5() {
		return this.rateId5;
	}

	public void setRateId5(BigDecimal rateId5) {
		this.rateId5 = rateId5;
	}

	public BigDecimal getRateAmt5() {
		return this.rateAmt5;
	}

	public void setRateAmt5(BigDecimal rateAmt5) {
		this.rateAmt5 = rateAmt5;
	}

	public BigDecimal getRateId6() {
		return this.rateId6;
	}

	public void setRateId6(BigDecimal rateId6) {
		this.rateId6 = rateId6;
	}

	public BigDecimal getRateAmt6() {
		return this.rateAmt6;
	}

	public void setRateAmt6(BigDecimal rateAmt6) {
		this.rateAmt6 = rateAmt6;
	}

	public BigDecimal getRateId7() {
		return this.rateId7;
	}

	public void setRateId7(BigDecimal rateId7) {
		this.rateId7 = rateId7;
	}

	public BigDecimal getRateAmt7() {
		return this.rateAmt7;
	}

	public void setRateAmt7(BigDecimal rateAmt7) {
		this.rateAmt7 = rateAmt7;
	}

	public BigDecimal getRateId8() {
		return this.rateId8;
	}

	public void setRateId8(BigDecimal rateId8) {
		this.rateId8 = rateId8;
	}

	public BigDecimal getRateAmt8() {
		return this.rateAmt8;
	}

	public void setRateAmt8(BigDecimal rateAmt8) {
		this.rateAmt8 = rateAmt8;
	}

	public BigDecimal getRateId9() {
		return this.rateId9;
	}

	public void setRateId9(BigDecimal rateId9) {
		this.rateId9 = rateId9;
	}

	public BigDecimal getRateAmt9() {
		return this.rateAmt9;
	}

	public void setRateAmt9(BigDecimal rateAmt9) {
		this.rateAmt9 = rateAmt9;
	}

	public BigDecimal getRateId10() {
		return this.rateId10;
	}

	public void setRateId10(BigDecimal rateId10) {
		this.rateId10 = rateId10;
	}

	public BigDecimal getRateAmt10() {
		return this.rateAmt10;
	}

	public void setRateAmt10(BigDecimal rateAmt10) {
		this.rateAmt10 = rateAmt10;
	}

	public BigDecimal getRateId11() {
		return this.rateId11;
	}

	public void setRateId11(BigDecimal rateId11) {
		this.rateId11 = rateId11;
	}

	public BigDecimal getRateAmt11() {
		return this.rateAmt11;
	}

	public void setRateAmt11(BigDecimal rateAmt11) {
		this.rateAmt11 = rateAmt11;
	}

	public BigDecimal getRateId12() {
		return this.rateId12;
	}

	public void setRateId12(BigDecimal rateId12) {
		this.rateId12 = rateId12;
	}

	public BigDecimal getRateAmt12() {
		return this.rateAmt12;
	}

	public void setRateAmt12(BigDecimal rateAmt12) {
		this.rateAmt12 = rateAmt12;
	}

	public BigDecimal getCallConnectionFee() {
		return this.callConnectionFee;
	}

	public void setCallConnectionFee(BigDecimal callConnectionFee) {
		this.callConnectionFee = callConnectionFee;
	}

	public BigDecimal getTier1Amt() {
		return this.tier1Amt;
	}

	public void setTier1Amt(BigDecimal tier1Amt) {
		this.tier1Amt = tier1Amt;
	}

	public BigDecimal getTier2Amt() {
		return this.tier2Amt;
	}

	public void setTier2Amt(BigDecimal tier2Amt) {
		this.tier2Amt = tier2Amt;
	}

	public BigDecimal getTier3Amt() {
		return this.tier3Amt;
	}

	public void setTier3Amt(BigDecimal tier3Amt) {
		this.tier3Amt = tier3Amt;
	}

	public BigDecimal getTotalBongAmt() {
		return this.totalBongAmt;
	}

	public void setTotalBongAmt(BigDecimal totalBongAmt) {
		this.totalBongAmt = totalBongAmt;
	}

	public BigDecimal getCustRateId1() {
		return this.custRateId1;
	}

	public void setCustRateId1(BigDecimal custRateId1) {
		this.custRateId1 = custRateId1;
	}

	public BigDecimal getCustRateId2() {
		return this.custRateId2;
	}

	public void setCustRateId2(BigDecimal custRateId2) {
		this.custRateId2 = custRateId2;
	}

	public BigDecimal getCustRateId3() {
		return this.custRateId3;
	}

	public void setCustRateId3(BigDecimal custRateId3) {
		this.custRateId3 = custRateId3;
	}

	public BigDecimal getCustRateId4() {
		return this.custRateId4;
	}

	public void setCustRateId4(BigDecimal custRateId4) {
		this.custRateId4 = custRateId4;
	}

	public BigDecimal getCustRateAmt1() {
		return this.custRateAmt1;
	}

	public void setCustRateAmt1(BigDecimal custRateAmt1) {
		this.custRateAmt1 = custRateAmt1;
	}

	public BigDecimal getCustRateAmt2() {
		return this.custRateAmt2;
	}

	public void setCustRateAmt2(BigDecimal custRateAmt2) {
		this.custRateAmt2 = custRateAmt2;
	}

	public BigDecimal getCustRateAmt3() {
		return this.custRateAmt3;
	}

	public void setCustRateAmt3(BigDecimal custRateAmt3) {
		this.custRateAmt3 = custRateAmt3;
	}

	public BigDecimal getCustRateAmt4() {
		return this.custRateAmt4;
	}

	public void setCustRateAmt4(BigDecimal custRateAmt4) {
		this.custRateAmt4 = custRateAmt4;
	}

}
