package com.rawabi.model;

// Generated Sep 19, 2012 12:44:25 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

/**
 * EvtBalanceTransfer generated by hbm2java
 */
public class EvtBalanceTransfer implements java.io.Serializable {

	private String eventId;
	private Date timestamp;
	private Subscriber subscriber;
	private BigDecimal amount;
	private String sessionId;
	private BigDecimal sessionType;
	private BigDecimal fromSubscriberId;
	private BigDecimal auditId;
	private Character removeFlag;

	public EvtBalanceTransfer() {
	}

	public EvtBalanceTransfer(String eventId, Subscriber subscriber,
			BigDecimal amount) {
		this.eventId = eventId;
		this.subscriber = subscriber;
		this.amount = amount;
	}

	public EvtBalanceTransfer(String eventId, Subscriber subscriber,
			BigDecimal amount, String sessionId, BigDecimal sessionType,
			BigDecimal fromSubscriberId, BigDecimal auditId,
			Character removeFlag) {
		this.eventId = eventId;
		this.subscriber = subscriber;
		this.amount = amount;
		this.sessionId = sessionId;
		this.sessionType = sessionType;
		this.fromSubscriberId = fromSubscriberId;
		this.auditId = auditId;
		this.removeFlag = removeFlag;
	}

	public String getEventId() {
		return this.eventId;
	}

	public void setEventId(String eventId) {
		this.eventId = eventId;
	}

	public Date getTimestamp() {
		return this.timestamp;
	}

	public void setTimestamp(Date timestamp) {
		this.timestamp = timestamp;
	}

	public Subscriber getSubscriber() {
		return this.subscriber;
	}

	public void setSubscriber(Subscriber subscriber) {
		this.subscriber = subscriber;
	}

	public BigDecimal getAmount() {
		return this.amount;
	}

	public void setAmount(BigDecimal amount) {
		this.amount = amount;
	}

	public String getSessionId() {
		return this.sessionId;
	}

	public void setSessionId(String sessionId) {
		this.sessionId = sessionId;
	}

	public BigDecimal getSessionType() {
		return this.sessionType;
	}

	public void setSessionType(BigDecimal sessionType) {
		this.sessionType = sessionType;
	}

	public BigDecimal getFromSubscriberId() {
		return this.fromSubscriberId;
	}

	public void setFromSubscriberId(BigDecimal fromSubscriberId) {
		this.fromSubscriberId = fromSubscriberId;
	}

	public BigDecimal getAuditId() {
		return this.auditId;
	}

	public void setAuditId(BigDecimal auditId) {
		this.auditId = auditId;
	}

	public Character getRemoveFlag() {
		return this.removeFlag;
	}

	public void setRemoveFlag(Character removeFlag) {
		this.removeFlag = removeFlag;
	}

}
