package com.rawabi.model;

// Generated Jul 30, 2012 10:19:37 AM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

/**
 * LockedPins generated by hbm2java
 */
public class LockedPins implements java.io.Serializable {

	private BigDecimal subscriberId;
	private Subscriber subscriber;
	private Date lockTime;
	private String sessionId;
	private String ipAddress;

	public LockedPins() {
	}

	public LockedPins(Subscriber subscriber) {
		this.subscriber = subscriber;
	}

	public LockedPins(Subscriber subscriber, Date lockTime, String sessionId,
			String ipAddress) {
		this.subscriber = subscriber;
		this.lockTime = lockTime;
		this.sessionId = sessionId;
		this.ipAddress = ipAddress;
	}

	public BigDecimal getSubscriberId() {
		return this.subscriberId;
	}

	public void setSubscriberId(BigDecimal subscriberId) {
		this.subscriberId = subscriberId;
	}

	public Subscriber getSubscriber() {
		return this.subscriber;
	}

	public void setSubscriber(Subscriber subscriber) {
		this.subscriber = subscriber;
	}

	public Date getLockTime() {
		return this.lockTime;
	}

	public void setLockTime(Date lockTime) {
		this.lockTime = lockTime;
	}

	public String getSessionId() {
		return this.sessionId;
	}

	public void setSessionId(String sessionId) {
		this.sessionId = sessionId;
	}

	public String getIpAddress() {
		return this.ipAddress;
	}

	public void setIpAddress(String ipAddress) {
		this.ipAddress = ipAddress;
	}

}
