package com.rawabi.model;

// Generated Sep 19, 2012 12:44:25 PM by Hibernate Tools 3.4.0.CR1

/**
 * OfferingServiceXref generated by hbm2java
 */
public class OfferingServiceXref implements java.io.Serializable {

	private OfferingServiceXrefId id;
	private ProductOffering productOffering;

	public OfferingServiceXref() {
	}

	public OfferingServiceXref(OfferingServiceXrefId id,
			ProductOffering productOffering) {
		this.id = id;
		this.productOffering = productOffering;
	}

	public OfferingServiceXrefId getId() {
		return this.id;
	}

	public void setId(OfferingServiceXrefId id) {
		this.id = id;
	}

	public ProductOffering getProductOffering() {
		return this.productOffering;
	}

	public void setProductOffering(ProductOffering productOffering) {
		this.productOffering = productOffering;
	}

}
