package com.rawabi.model;

// Generated Jul 30, 2012 10:19:37 AM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;

/**
 * OfferingServiceXrefId generated by hbm2java
 */
public class OfferingServiceXrefId implements java.io.Serializable {

	private BigDecimal offeringId;
	private BigDecimal serviceId;

	public OfferingServiceXrefId() {
	}

	public OfferingServiceXrefId(BigDecimal offeringId, BigDecimal serviceId) {
		this.offeringId = offeringId;
		this.serviceId = serviceId;
	}

	public BigDecimal getOfferingId() {
		return this.offeringId;
	}

	public void setOfferingId(BigDecimal offeringId) {
		this.offeringId = offeringId;
	}

	public BigDecimal getServiceId() {
		return this.serviceId;
	}

	public void setServiceId(BigDecimal serviceId) {
		this.serviceId = serviceId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof OfferingServiceXrefId))
			return false;
		OfferingServiceXrefId castOther = (OfferingServiceXrefId) other;

		return ((this.getOfferingId() == castOther.getOfferingId()) || (this
				.getOfferingId() != null && castOther.getOfferingId() != null && this
				.getOfferingId().equals(castOther.getOfferingId())))
				&& ((this.getServiceId() == castOther.getServiceId()) || (this
						.getServiceId() != null
						&& castOther.getServiceId() != null && this
						.getServiceId().equals(castOther.getServiceId())));
	}

	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getOfferingId() == null ? 0 : this.getOfferingId()
						.hashCode());
		result = 37 * result
				+ (getServiceId() == null ? 0 : this.getServiceId().hashCode());
		return result;
	}

}
