package com.rawabi.model;

// Generated Sep 19, 2012 12:44:25 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

/**
 * PreActivatedSubscribers generated by hbm2java
 */
public class PreActivatedSubscribers implements java.io.Serializable {

	private BigDecimal subscriberId;
	private EvtPrepaidActivation evtPrepaidActivation;
	private ServiceProvider serviceProvider;
	private Lot lot;
	private String pin;
	private String pinPassword;
	private BigDecimal lotSeqNumber;
	private Character activationFlag;
	private Character allowPinOnlyLoginFlag;
	private Character disabledFlag;
	private Date activationDate;
	private String confReslessModPasscode;
	private String confReslessPasscode;
	private String lotControlNumber;
	private String posEventId;

	public PreActivatedSubscribers() {
	}

	public PreActivatedSubscribers(BigDecimal subscriberId,
			ServiceProvider serviceProvider, Lot lot, String pin,
			String pinPassword) {
		this.subscriberId = subscriberId;
		this.serviceProvider = serviceProvider;
		this.lot = lot;
		this.pin = pin;
		this.pinPassword = pinPassword;
	}

	public PreActivatedSubscribers(BigDecimal subscriberId,
			EvtPrepaidActivation evtPrepaidActivation,
			ServiceProvider serviceProvider, Lot lot, String pin,
			String pinPassword, BigDecimal lotSeqNumber,
			Character activationFlag, Character allowPinOnlyLoginFlag,
			Character disabledFlag, Date activationDate,
			String confReslessModPasscode, String confReslessPasscode,
			String lotControlNumber, String posEventId) {
		this.subscriberId = subscriberId;
		this.evtPrepaidActivation = evtPrepaidActivation;
		this.serviceProvider = serviceProvider;
		this.lot = lot;
		this.pin = pin;
		this.pinPassword = pinPassword;
		this.lotSeqNumber = lotSeqNumber;
		this.activationFlag = activationFlag;
		this.allowPinOnlyLoginFlag = allowPinOnlyLoginFlag;
		this.disabledFlag = disabledFlag;
		this.activationDate = activationDate;
		this.confReslessModPasscode = confReslessModPasscode;
		this.confReslessPasscode = confReslessPasscode;
		this.lotControlNumber = lotControlNumber;
		this.posEventId = posEventId;
	}

	public BigDecimal getSubscriberId() {
		return this.subscriberId;
	}

	public void setSubscriberId(BigDecimal subscriberId) {
		this.subscriberId = subscriberId;
	}

	public EvtPrepaidActivation getEvtPrepaidActivation() {
		return this.evtPrepaidActivation;
	}

	public void setEvtPrepaidActivation(
			EvtPrepaidActivation evtPrepaidActivation) {
		this.evtPrepaidActivation = evtPrepaidActivation;
	}

	public ServiceProvider getServiceProvider() {
		return this.serviceProvider;
	}

	public void setServiceProvider(ServiceProvider serviceProvider) {
		this.serviceProvider = serviceProvider;
	}

	public Lot getLot() {
		return this.lot;
	}

	public void setLot(Lot lot) {
		this.lot = lot;
	}

	public String getPin() {
		return this.pin;
	}

	public void setPin(String pin) {
		this.pin = pin;
	}

	public String getPinPassword() {
		return this.pinPassword;
	}

	public void setPinPassword(String pinPassword) {
		this.pinPassword = pinPassword;
	}

	public BigDecimal getLotSeqNumber() {
		return this.lotSeqNumber;
	}

	public void setLotSeqNumber(BigDecimal lotSeqNumber) {
		this.lotSeqNumber = lotSeqNumber;
	}

	public Character getActivationFlag() {
		return this.activationFlag;
	}

	public void setActivationFlag(Character activationFlag) {
		this.activationFlag = activationFlag;
	}

	public Character getAllowPinOnlyLoginFlag() {
		return this.allowPinOnlyLoginFlag;
	}

	public void setAllowPinOnlyLoginFlag(Character allowPinOnlyLoginFlag) {
		this.allowPinOnlyLoginFlag = allowPinOnlyLoginFlag;
	}

	public Character getDisabledFlag() {
		return this.disabledFlag;
	}

	public void setDisabledFlag(Character disabledFlag) {
		this.disabledFlag = disabledFlag;
	}

	public Date getActivationDate() {
		return this.activationDate;
	}

	public void setActivationDate(Date activationDate) {
		this.activationDate = activationDate;
	}

	public String getConfReslessModPasscode() {
		return this.confReslessModPasscode;
	}

	public void setConfReslessModPasscode(String confReslessModPasscode) {
		this.confReslessModPasscode = confReslessModPasscode;
	}

	public String getConfReslessPasscode() {
		return this.confReslessPasscode;
	}

	public void setConfReslessPasscode(String confReslessPasscode) {
		this.confReslessPasscode = confReslessPasscode;
	}

	public String getLotControlNumber() {
		return this.lotControlNumber;
	}

	public void setLotControlNumber(String lotControlNumber) {
		this.lotControlNumber = lotControlNumber;
	}

	public String getPosEventId() {
		return this.posEventId;
	}

	public void setPosEventId(String posEventId) {
		this.posEventId = posEventId;
	}

}
