package com.rawabi.model;

// Generated Jul 24, 2012 12:30:09 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

/**
 * PreActivatedSubscribers generated by hbm2java
 */
public class PreActivatedSubscribers implements java.io.Serializable {

	private BigDecimal subscriberId;
	private ServiceProvider serviceProvider;
	private BigDecimal lotId;
	private String pin;
	private String pinPassword;
	private BigDecimal lotSeqNumber;
	private Character disabledFlag;
	private Character activationFlag;
	private Character allowPinOnlyLoginFlag;
	private Date activationDate;
	private String activationId;
	private String confReslessModPasscode;
	private String confReslessPasscode;
	private String lotControlNumber;
	private String posEventId;

	public PreActivatedSubscribers() {
	}

	public PreActivatedSubscribers(BigDecimal subscriberId,
			ServiceProvider serviceProvider, BigDecimal lotId, String pin,
			String pinPassword) {
		this.subscriberId = subscriberId;
		this.serviceProvider = serviceProvider;
		this.lotId = lotId;
		this.pin = pin;
		this.pinPassword = pinPassword;
	}

	public PreActivatedSubscribers(BigDecimal subscriberId,
			ServiceProvider serviceProvider, BigDecimal lotId, String pin,
			String pinPassword, BigDecimal lotSeqNumber,
			Character disabledFlag, Character activationFlag,
			Character allowPinOnlyLoginFlag, Date activationDate,
			String activationId, String confReslessModPasscode,
			String confReslessPasscode, String lotControlNumber,
			String posEventId) {
		this.subscriberId = subscriberId;
		this.serviceProvider = serviceProvider;
		this.lotId = lotId;
		this.pin = pin;
		this.pinPassword = pinPassword;
		this.lotSeqNumber = lotSeqNumber;
		this.disabledFlag = disabledFlag;
		this.activationFlag = activationFlag;
		this.allowPinOnlyLoginFlag = allowPinOnlyLoginFlag;
		this.activationDate = activationDate;
		this.activationId = activationId;
		this.confReslessModPasscode = confReslessModPasscode;
		this.confReslessPasscode = confReslessPasscode;
		this.lotControlNumber = lotControlNumber;
		this.posEventId = posEventId;
	}

	public BigDecimal getSubscriberId() {
		return this.subscriberId;
	}

	public void setSubscriberId(BigDecimal subscriberId) {
		this.subscriberId = subscriberId;
	}

	public ServiceProvider getServiceProvider() {
		return this.serviceProvider;
	}

	public void setServiceProvider(ServiceProvider serviceProvider) {
		this.serviceProvider = serviceProvider;
	}

	public BigDecimal getLotId() {
		return this.lotId;
	}

	public void setLotId(BigDecimal lotId) {
		this.lotId = lotId;
	}

	public String getPin() {
		return this.pin;
	}

	public void setPin(String pin) {
		this.pin = pin;
	}

	public String getPinPassword() {
		return this.pinPassword;
	}

	public void setPinPassword(String pinPassword) {
		this.pinPassword = pinPassword;
	}

	public BigDecimal getLotSeqNumber() {
		return this.lotSeqNumber;
	}

	public void setLotSeqNumber(BigDecimal lotSeqNumber) {
		this.lotSeqNumber = lotSeqNumber;
	}

	public Character getDisabledFlag() {
		return this.disabledFlag;
	}

	public void setDisabledFlag(Character disabledFlag) {
		this.disabledFlag = disabledFlag;
	}

	public Character getActivationFlag() {
		return this.activationFlag;
	}

	public void setActivationFlag(Character activationFlag) {
		this.activationFlag = activationFlag;
	}

	public Character getAllowPinOnlyLoginFlag() {
		return this.allowPinOnlyLoginFlag;
	}

	public void setAllowPinOnlyLoginFlag(Character allowPinOnlyLoginFlag) {
		this.allowPinOnlyLoginFlag = allowPinOnlyLoginFlag;
	}

	public Date getActivationDate() {
		return this.activationDate;
	}

	public void setActivationDate(Date activationDate) {
		this.activationDate = activationDate;
	}

	public String getActivationId() {
		return this.activationId;
	}

	public void setActivationId(String activationId) {
		this.activationId = activationId;
	}

	public String getConfReslessModPasscode() {
		return this.confReslessModPasscode;
	}

	public void setConfReslessModPasscode(String confReslessModPasscode) {
		this.confReslessModPasscode = confReslessModPasscode;
	}

	public String getConfReslessPasscode() {
		return this.confReslessPasscode;
	}

	public void setConfReslessPasscode(String confReslessPasscode) {
		this.confReslessPasscode = confReslessPasscode;
	}

	public String getLotControlNumber() {
		return this.lotControlNumber;
	}

	public void setLotControlNumber(String lotControlNumber) {
		this.lotControlNumber = lotControlNumber;
	}

	public String getPosEventId() {
		return this.posEventId;
	}

	public void setPosEventId(String posEventId) {
		this.posEventId = posEventId;
	}

}
