package com.rawabi.model;

// Generated Jul 24, 2012 12:30:09 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * ProductOffering generated by hbm2java
 */
public class ProductOffering implements java.io.Serializable {

	private BigDecimal offeringId;
	private ServiceProvider serviceProvider;
	private BigDecimal currencyId;
	private BigDecimal languageId;
	private BigDecimal pinLength;
	private BigDecimal expirationType;
	private char balXferFlag;
	private char ccRechargeFlag;
	private char balanceSweepFlag;
	private char creditCardReqFlag;
	private char emailFlag;
	private BigDecimal subSignupStatus;
	private char creditCardValidFlag;
	private char allowCorpAcctFlag;
	private char aniAuthFlag;
	private char requireAniAuthFlag;
	private char deletedFlag;
	private char popdRateCallsFlag;
	private char popdCreditLimitFlag;
	private char accessNumOfferingRequired;
	private char customRatesFlag;
	private char balXferDisableSub;
	private char ivrAcctBalUnitsFlag;
	private char firmCreditLimitFlag;
	private Character primaryFlag;
	private Date expirationDate;
	private BigDecimal numExpirationDays;
	private BigDecimal ppMinBalance;
	private BigDecimal ppMaxBalance;
	private BigDecimal minRecharge;
	private BigDecimal maxRecharge;
	private BigDecimal billingType;
	private BigDecimal ccMaxSubweek;
	private BigDecimal ccMaxSubmonth;
	private BigDecimal ccMaxCardweek;
	private BigDecimal ccMaxCardmonth;
	private BigDecimal ccRechargeAmount1;
	private BigDecimal ccRechargeAmount2;
	private BigDecimal ccRechargeAmount3;
	private BigDecimal ccRechargeAmount4;
	private BigDecimal popdCreditLimit;
	private BigDecimal clmBalResetDay;
	private BigDecimal dialingPlanId;
	private BigDecimal ccRechargeAmount5;
	private BigDecimal ccRechargeAmount6;
	private BigDecimal creditLimitWarning;
	private String name;
	private String description;
	private Set<AccountActivity> accountActivities = new HashSet<AccountActivity>(
			0);

	public ProductOffering() {
	}

	public ProductOffering(BigDecimal offeringId,
			ServiceProvider serviceProvider, BigDecimal currencyId,
			BigDecimal languageId, BigDecimal pinLength,
			BigDecimal expirationType, char balXferFlag, char ccRechargeFlag,
			char balanceSweepFlag, char creditCardReqFlag, char emailFlag,
			BigDecimal subSignupStatus, char creditCardValidFlag,
			char allowCorpAcctFlag, char aniAuthFlag, char requireAniAuthFlag,
			char deletedFlag, char popdRateCallsFlag, char popdCreditLimitFlag,
			char accessNumOfferingRequired, char customRatesFlag,
			char balXferDisableSub, char ivrAcctBalUnitsFlag,
			char firmCreditLimitFlag) {
		this.offeringId = offeringId;
		this.serviceProvider = serviceProvider;
		this.currencyId = currencyId;
		this.languageId = languageId;
		this.pinLength = pinLength;
		this.expirationType = expirationType;
		this.balXferFlag = balXferFlag;
		this.ccRechargeFlag = ccRechargeFlag;
		this.balanceSweepFlag = balanceSweepFlag;
		this.creditCardReqFlag = creditCardReqFlag;
		this.emailFlag = emailFlag;
		this.subSignupStatus = subSignupStatus;
		this.creditCardValidFlag = creditCardValidFlag;
		this.allowCorpAcctFlag = allowCorpAcctFlag;
		this.aniAuthFlag = aniAuthFlag;
		this.requireAniAuthFlag = requireAniAuthFlag;
		this.deletedFlag = deletedFlag;
		this.popdRateCallsFlag = popdRateCallsFlag;
		this.popdCreditLimitFlag = popdCreditLimitFlag;
		this.accessNumOfferingRequired = accessNumOfferingRequired;
		this.customRatesFlag = customRatesFlag;
		this.balXferDisableSub = balXferDisableSub;
		this.ivrAcctBalUnitsFlag = ivrAcctBalUnitsFlag;
		this.firmCreditLimitFlag = firmCreditLimitFlag;
	}

	public ProductOffering(BigDecimal offeringId,
			ServiceProvider serviceProvider, BigDecimal currencyId,
			BigDecimal languageId, BigDecimal pinLength,
			BigDecimal expirationType, char balXferFlag, char ccRechargeFlag,
			char balanceSweepFlag, char creditCardReqFlag, char emailFlag,
			BigDecimal subSignupStatus, char creditCardValidFlag,
			char allowCorpAcctFlag, char aniAuthFlag, char requireAniAuthFlag,
			char deletedFlag, char popdRateCallsFlag, char popdCreditLimitFlag,
			char accessNumOfferingRequired, char customRatesFlag,
			char balXferDisableSub, char ivrAcctBalUnitsFlag,
			char firmCreditLimitFlag, Character primaryFlag,
			Date expirationDate, BigDecimal numExpirationDays,
			BigDecimal ppMinBalance, BigDecimal ppMaxBalance,
			BigDecimal minRecharge, BigDecimal maxRecharge,
			BigDecimal billingType, BigDecimal ccMaxSubweek,
			BigDecimal ccMaxSubmonth, BigDecimal ccMaxCardweek,
			BigDecimal ccMaxCardmonth, BigDecimal ccRechargeAmount1,
			BigDecimal ccRechargeAmount2, BigDecimal ccRechargeAmount3,
			BigDecimal ccRechargeAmount4, BigDecimal popdCreditLimit,
			BigDecimal clmBalResetDay, BigDecimal dialingPlanId,
			BigDecimal ccRechargeAmount5, BigDecimal ccRechargeAmount6,
			BigDecimal creditLimitWarning, String name, String description,
			Set<AccountActivity> accountActivities) {
		this.offeringId = offeringId;
		this.serviceProvider = serviceProvider;
		this.currencyId = currencyId;
		this.languageId = languageId;
		this.pinLength = pinLength;
		this.expirationType = expirationType;
		this.balXferFlag = balXferFlag;
		this.ccRechargeFlag = ccRechargeFlag;
		this.balanceSweepFlag = balanceSweepFlag;
		this.creditCardReqFlag = creditCardReqFlag;
		this.emailFlag = emailFlag;
		this.subSignupStatus = subSignupStatus;
		this.creditCardValidFlag = creditCardValidFlag;
		this.allowCorpAcctFlag = allowCorpAcctFlag;
		this.aniAuthFlag = aniAuthFlag;
		this.requireAniAuthFlag = requireAniAuthFlag;
		this.deletedFlag = deletedFlag;
		this.popdRateCallsFlag = popdRateCallsFlag;
		this.popdCreditLimitFlag = popdCreditLimitFlag;
		this.accessNumOfferingRequired = accessNumOfferingRequired;
		this.customRatesFlag = customRatesFlag;
		this.balXferDisableSub = balXferDisableSub;
		this.ivrAcctBalUnitsFlag = ivrAcctBalUnitsFlag;
		this.firmCreditLimitFlag = firmCreditLimitFlag;
		this.primaryFlag = primaryFlag;
		this.expirationDate = expirationDate;
		this.numExpirationDays = numExpirationDays;
		this.ppMinBalance = ppMinBalance;
		this.ppMaxBalance = ppMaxBalance;
		this.minRecharge = minRecharge;
		this.maxRecharge = maxRecharge;
		this.billingType = billingType;
		this.ccMaxSubweek = ccMaxSubweek;
		this.ccMaxSubmonth = ccMaxSubmonth;
		this.ccMaxCardweek = ccMaxCardweek;
		this.ccMaxCardmonth = ccMaxCardmonth;
		this.ccRechargeAmount1 = ccRechargeAmount1;
		this.ccRechargeAmount2 = ccRechargeAmount2;
		this.ccRechargeAmount3 = ccRechargeAmount3;
		this.ccRechargeAmount4 = ccRechargeAmount4;
		this.popdCreditLimit = popdCreditLimit;
		this.clmBalResetDay = clmBalResetDay;
		this.dialingPlanId = dialingPlanId;
		this.ccRechargeAmount5 = ccRechargeAmount5;
		this.ccRechargeAmount6 = ccRechargeAmount6;
		this.creditLimitWarning = creditLimitWarning;
		this.name = name;
		this.description = description;
		this.accountActivities = accountActivities;
	}

	public BigDecimal getOfferingId() {
		return this.offeringId;
	}

	public void setOfferingId(BigDecimal offeringId) {
		this.offeringId = offeringId;
	}

	public ServiceProvider getServiceProvider() {
		return this.serviceProvider;
	}

	public void setServiceProvider(ServiceProvider serviceProvider) {
		this.serviceProvider = serviceProvider;
	}

	public BigDecimal getCurrencyId() {
		return this.currencyId;
	}

	public void setCurrencyId(BigDecimal currencyId) {
		this.currencyId = currencyId;
	}

	public BigDecimal getLanguageId() {
		return this.languageId;
	}

	public void setLanguageId(BigDecimal languageId) {
		this.languageId = languageId;
	}

	public BigDecimal getPinLength() {
		return this.pinLength;
	}

	public void setPinLength(BigDecimal pinLength) {
		this.pinLength = pinLength;
	}

	public BigDecimal getExpirationType() {
		return this.expirationType;
	}

	public void setExpirationType(BigDecimal expirationType) {
		this.expirationType = expirationType;
	}

	public char getBalXferFlag() {
		return this.balXferFlag;
	}

	public void setBalXferFlag(char balXferFlag) {
		this.balXferFlag = balXferFlag;
	}

	public char getCcRechargeFlag() {
		return this.ccRechargeFlag;
	}

	public void setCcRechargeFlag(char ccRechargeFlag) {
		this.ccRechargeFlag = ccRechargeFlag;
	}

	public char getBalanceSweepFlag() {
		return this.balanceSweepFlag;
	}

	public void setBalanceSweepFlag(char balanceSweepFlag) {
		this.balanceSweepFlag = balanceSweepFlag;
	}

	public char getCreditCardReqFlag() {
		return this.creditCardReqFlag;
	}

	public void setCreditCardReqFlag(char creditCardReqFlag) {
		this.creditCardReqFlag = creditCardReqFlag;
	}

	public char getEmailFlag() {
		return this.emailFlag;
	}

	public void setEmailFlag(char emailFlag) {
		this.emailFlag = emailFlag;
	}

	public BigDecimal getSubSignupStatus() {
		return this.subSignupStatus;
	}

	public void setSubSignupStatus(BigDecimal subSignupStatus) {
		this.subSignupStatus = subSignupStatus;
	}

	public char getCreditCardValidFlag() {
		return this.creditCardValidFlag;
	}

	public void setCreditCardValidFlag(char creditCardValidFlag) {
		this.creditCardValidFlag = creditCardValidFlag;
	}

	public char getAllowCorpAcctFlag() {
		return this.allowCorpAcctFlag;
	}

	public void setAllowCorpAcctFlag(char allowCorpAcctFlag) {
		this.allowCorpAcctFlag = allowCorpAcctFlag;
	}

	public char getAniAuthFlag() {
		return this.aniAuthFlag;
	}

	public void setAniAuthFlag(char aniAuthFlag) {
		this.aniAuthFlag = aniAuthFlag;
	}

	public char getRequireAniAuthFlag() {
		return this.requireAniAuthFlag;
	}

	public void setRequireAniAuthFlag(char requireAniAuthFlag) {
		this.requireAniAuthFlag = requireAniAuthFlag;
	}

	public char getDeletedFlag() {
		return this.deletedFlag;
	}

	public void setDeletedFlag(char deletedFlag) {
		this.deletedFlag = deletedFlag;
	}

	public char getPopdRateCallsFlag() {
		return this.popdRateCallsFlag;
	}

	public void setPopdRateCallsFlag(char popdRateCallsFlag) {
		this.popdRateCallsFlag = popdRateCallsFlag;
	}

	public char getPopdCreditLimitFlag() {
		return this.popdCreditLimitFlag;
	}

	public void setPopdCreditLimitFlag(char popdCreditLimitFlag) {
		this.popdCreditLimitFlag = popdCreditLimitFlag;
	}

	public char getAccessNumOfferingRequired() {
		return this.accessNumOfferingRequired;
	}

	public void setAccessNumOfferingRequired(char accessNumOfferingRequired) {
		this.accessNumOfferingRequired = accessNumOfferingRequired;
	}

	public char getCustomRatesFlag() {
		return this.customRatesFlag;
	}

	public void setCustomRatesFlag(char customRatesFlag) {
		this.customRatesFlag = customRatesFlag;
	}

	public char getBalXferDisableSub() {
		return this.balXferDisableSub;
	}

	public void setBalXferDisableSub(char balXferDisableSub) {
		this.balXferDisableSub = balXferDisableSub;
	}

	public char getIvrAcctBalUnitsFlag() {
		return this.ivrAcctBalUnitsFlag;
	}

	public void setIvrAcctBalUnitsFlag(char ivrAcctBalUnitsFlag) {
		this.ivrAcctBalUnitsFlag = ivrAcctBalUnitsFlag;
	}

	public char getFirmCreditLimitFlag() {
		return this.firmCreditLimitFlag;
	}

	public void setFirmCreditLimitFlag(char firmCreditLimitFlag) {
		this.firmCreditLimitFlag = firmCreditLimitFlag;
	}

	public Character getPrimaryFlag() {
		return this.primaryFlag;
	}

	public void setPrimaryFlag(Character primaryFlag) {
		this.primaryFlag = primaryFlag;
	}

	public Date getExpirationDate() {
		return this.expirationDate;
	}

	public void setExpirationDate(Date expirationDate) {
		this.expirationDate = expirationDate;
	}

	public BigDecimal getNumExpirationDays() {
		return this.numExpirationDays;
	}

	public void setNumExpirationDays(BigDecimal numExpirationDays) {
		this.numExpirationDays = numExpirationDays;
	}

	public BigDecimal getPpMinBalance() {
		return this.ppMinBalance;
	}

	public void setPpMinBalance(BigDecimal ppMinBalance) {
		this.ppMinBalance = ppMinBalance;
	}

	public BigDecimal getPpMaxBalance() {
		return this.ppMaxBalance;
	}

	public void setPpMaxBalance(BigDecimal ppMaxBalance) {
		this.ppMaxBalance = ppMaxBalance;
	}

	public BigDecimal getMinRecharge() {
		return this.minRecharge;
	}

	public void setMinRecharge(BigDecimal minRecharge) {
		this.minRecharge = minRecharge;
	}

	public BigDecimal getMaxRecharge() {
		return this.maxRecharge;
	}

	public void setMaxRecharge(BigDecimal maxRecharge) {
		this.maxRecharge = maxRecharge;
	}

	public BigDecimal getBillingType() {
		return this.billingType;
	}

	public void setBillingType(BigDecimal billingType) {
		this.billingType = billingType;
	}

	public BigDecimal getCcMaxSubweek() {
		return this.ccMaxSubweek;
	}

	public void setCcMaxSubweek(BigDecimal ccMaxSubweek) {
		this.ccMaxSubweek = ccMaxSubweek;
	}

	public BigDecimal getCcMaxSubmonth() {
		return this.ccMaxSubmonth;
	}

	public void setCcMaxSubmonth(BigDecimal ccMaxSubmonth) {
		this.ccMaxSubmonth = ccMaxSubmonth;
	}

	public BigDecimal getCcMaxCardweek() {
		return this.ccMaxCardweek;
	}

	public void setCcMaxCardweek(BigDecimal ccMaxCardweek) {
		this.ccMaxCardweek = ccMaxCardweek;
	}

	public BigDecimal getCcMaxCardmonth() {
		return this.ccMaxCardmonth;
	}

	public void setCcMaxCardmonth(BigDecimal ccMaxCardmonth) {
		this.ccMaxCardmonth = ccMaxCardmonth;
	}

	public BigDecimal getCcRechargeAmount1() {
		return this.ccRechargeAmount1;
	}

	public void setCcRechargeAmount1(BigDecimal ccRechargeAmount1) {
		this.ccRechargeAmount1 = ccRechargeAmount1;
	}

	public BigDecimal getCcRechargeAmount2() {
		return this.ccRechargeAmount2;
	}

	public void setCcRechargeAmount2(BigDecimal ccRechargeAmount2) {
		this.ccRechargeAmount2 = ccRechargeAmount2;
	}

	public BigDecimal getCcRechargeAmount3() {
		return this.ccRechargeAmount3;
	}

	public void setCcRechargeAmount3(BigDecimal ccRechargeAmount3) {
		this.ccRechargeAmount3 = ccRechargeAmount3;
	}

	public BigDecimal getCcRechargeAmount4() {
		return this.ccRechargeAmount4;
	}

	public void setCcRechargeAmount4(BigDecimal ccRechargeAmount4) {
		this.ccRechargeAmount4 = ccRechargeAmount4;
	}

	public BigDecimal getPopdCreditLimit() {
		return this.popdCreditLimit;
	}

	public void setPopdCreditLimit(BigDecimal popdCreditLimit) {
		this.popdCreditLimit = popdCreditLimit;
	}

	public BigDecimal getClmBalResetDay() {
		return this.clmBalResetDay;
	}

	public void setClmBalResetDay(BigDecimal clmBalResetDay) {
		this.clmBalResetDay = clmBalResetDay;
	}

	public BigDecimal getDialingPlanId() {
		return this.dialingPlanId;
	}

	public void setDialingPlanId(BigDecimal dialingPlanId) {
		this.dialingPlanId = dialingPlanId;
	}

	public BigDecimal getCcRechargeAmount5() {
		return this.ccRechargeAmount5;
	}

	public void setCcRechargeAmount5(BigDecimal ccRechargeAmount5) {
		this.ccRechargeAmount5 = ccRechargeAmount5;
	}

	public BigDecimal getCcRechargeAmount6() {
		return this.ccRechargeAmount6;
	}

	public void setCcRechargeAmount6(BigDecimal ccRechargeAmount6) {
		this.ccRechargeAmount6 = ccRechargeAmount6;
	}

	public BigDecimal getCreditLimitWarning() {
		return this.creditLimitWarning;
	}

	public void setCreditLimitWarning(BigDecimal creditLimitWarning) {
		this.creditLimitWarning = creditLimitWarning;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Set<AccountActivity> getAccountActivities() {
		return this.accountActivities;
	}

	public void setAccountActivities(Set<AccountActivity> accountActivities) {
		this.accountActivities = accountActivities;
	}

}
