package com.rawabi.model;

// Generated Jul 30, 2012 10:19:37 AM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * ServiceProvider generated by hbm2java
 */
public class ServiceProvider implements java.io.Serializable {

	private BigDecimal serviceProviderId;
	private String logonKey;
	private char deletedFlag;
	private char disabledFlag;
	private char enableMaxSessions;
	private char enableMaxCalls;
	private Character allowPhoneNumberMaintenance;
	private Character enableMaxSessForParent;
	private Character enableMaxCallsForParent;
	private Character voicemailFlag;
	private Character pstnEgressFlag;
	private String serviceProviderCode;
	private String name;
	private String description;
	private BigDecimal maxSimultaneousCalls;
	private BigDecimal maxCurrentCalls;
	private BigDecimal maxSimultaneousSessions;
	private BigDecimal availableSessions;
	private BigDecimal availableCalls;
	private String ecrcNumber;
	private String forwardingNbr1;
	private String forwardingNbr2;
	private String forwardingNbr3;
	private String psap1;
	private String psap2;
	private String sipRealm;
	private String reportingPassword;
	private String primarySoftswitchIp;
	private String backupSoftswitchIp;
	private String proxyServer;
	private Character creditLimitFlag;
	private Character creditWarningMethod;
	private BigDecimal creditLimit;
	private BigDecimal creditUsed;
	private BigDecimal creditWarningThresholdPct;
	private BigDecimal creditWarningThresholdAmt;
	private char pinGenLimitFlag;
	private BigDecimal pinGenLimit;
	private BigDecimal pinGenAvailable;
	private BigDecimal pinGenSelfNotification;
	private BigDecimal pinGenParentNotification;
	private Set<SubAuthAni> subAuthAnis = new HashSet<SubAuthAni>(0);
	private Set<PreActivatedSubscribers> preActivatedSubscriberses = new HashSet<PreActivatedSubscribers>(
			0);
	private Set<ProductOffering> productOfferings = new HashSet<ProductOffering>(
			0);
	private Set<ServiceProviderSettings> serviceProviderSettingses = new HashSet<ServiceProviderSettings>(
			0);
	private Set<AccountActivity> accountActivities = new HashSet<AccountActivity>(
			0);
	private Set<AccessNumber> accessNumbers = new HashSet<AccessNumber>(0);
	private Set<Lot> lots = new HashSet<Lot>(0);

	public ServiceProvider() {
	}

	public ServiceProvider(BigDecimal serviceProviderId, String logonKey,
			char deletedFlag, char disabledFlag, char enableMaxSessions,
			char enableMaxCalls, char pinGenLimitFlag) {
		this.serviceProviderId = serviceProviderId;
		this.logonKey = logonKey;
		this.deletedFlag = deletedFlag;
		this.disabledFlag = disabledFlag;
		this.enableMaxSessions = enableMaxSessions;
		this.enableMaxCalls = enableMaxCalls;
		this.pinGenLimitFlag = pinGenLimitFlag;
	}

	public ServiceProvider(BigDecimal serviceProviderId, String logonKey,
			char deletedFlag, char disabledFlag, char enableMaxSessions,
			char enableMaxCalls, Character allowPhoneNumberMaintenance,
			Character enableMaxSessForParent,
			Character enableMaxCallsForParent, Character voicemailFlag,
			Character pstnEgressFlag, String serviceProviderCode, String name,
			String description, BigDecimal maxSimultaneousCalls,
			BigDecimal maxCurrentCalls, BigDecimal maxSimultaneousSessions,
			BigDecimal availableSessions, BigDecimal availableCalls,
			String ecrcNumber, String forwardingNbr1, String forwardingNbr2,
			String forwardingNbr3, String psap1, String psap2, String sipRealm,
			String reportingPassword, String primarySoftswitchIp,
			String backupSoftswitchIp, String proxyServer,
			Character creditLimitFlag, Character creditWarningMethod,
			BigDecimal creditLimit, BigDecimal creditUsed,
			BigDecimal creditWarningThresholdPct,
			BigDecimal creditWarningThresholdAmt, char pinGenLimitFlag,
			BigDecimal pinGenLimit, BigDecimal pinGenAvailable,
			BigDecimal pinGenSelfNotification,
			BigDecimal pinGenParentNotification, Set<SubAuthAni> subAuthAnis,
			Set<PreActivatedSubscribers> preActivatedSubscriberses,
			Set<ProductOffering> productOfferings,
			Set<ServiceProviderSettings> serviceProviderSettingses,
			Set<AccountActivity> accountActivities,
			Set<AccessNumber> accessNumbers, Set<Lot> lots) {
		this.serviceProviderId = serviceProviderId;
		this.logonKey = logonKey;
		this.deletedFlag = deletedFlag;
		this.disabledFlag = disabledFlag;
		this.enableMaxSessions = enableMaxSessions;
		this.enableMaxCalls = enableMaxCalls;
		this.allowPhoneNumberMaintenance = allowPhoneNumberMaintenance;
		this.enableMaxSessForParent = enableMaxSessForParent;
		this.enableMaxCallsForParent = enableMaxCallsForParent;
		this.voicemailFlag = voicemailFlag;
		this.pstnEgressFlag = pstnEgressFlag;
		this.serviceProviderCode = serviceProviderCode;
		this.name = name;
		this.description = description;
		this.maxSimultaneousCalls = maxSimultaneousCalls;
		this.maxCurrentCalls = maxCurrentCalls;
		this.maxSimultaneousSessions = maxSimultaneousSessions;
		this.availableSessions = availableSessions;
		this.availableCalls = availableCalls;
		this.ecrcNumber = ecrcNumber;
		this.forwardingNbr1 = forwardingNbr1;
		this.forwardingNbr2 = forwardingNbr2;
		this.forwardingNbr3 = forwardingNbr3;
		this.psap1 = psap1;
		this.psap2 = psap2;
		this.sipRealm = sipRealm;
		this.reportingPassword = reportingPassword;
		this.primarySoftswitchIp = primarySoftswitchIp;
		this.backupSoftswitchIp = backupSoftswitchIp;
		this.proxyServer = proxyServer;
		this.creditLimitFlag = creditLimitFlag;
		this.creditWarningMethod = creditWarningMethod;
		this.creditLimit = creditLimit;
		this.creditUsed = creditUsed;
		this.creditWarningThresholdPct = creditWarningThresholdPct;
		this.creditWarningThresholdAmt = creditWarningThresholdAmt;
		this.pinGenLimitFlag = pinGenLimitFlag;
		this.pinGenLimit = pinGenLimit;
		this.pinGenAvailable = pinGenAvailable;
		this.pinGenSelfNotification = pinGenSelfNotification;
		this.pinGenParentNotification = pinGenParentNotification;
		this.subAuthAnis = subAuthAnis;
		this.preActivatedSubscriberses = preActivatedSubscriberses;
		this.productOfferings = productOfferings;
		this.serviceProviderSettingses = serviceProviderSettingses;
		this.accountActivities = accountActivities;
		this.accessNumbers = accessNumbers;
		this.lots = lots;
	}

	public BigDecimal getServiceProviderId() {
		return this.serviceProviderId;
	}

	public void setServiceProviderId(BigDecimal serviceProviderId) {
		this.serviceProviderId = serviceProviderId;
	}

	public String getLogonKey() {
		return this.logonKey;
	}

	public void setLogonKey(String logonKey) {
		this.logonKey = logonKey;
	}

	public char getDeletedFlag() {
		return this.deletedFlag;
	}

	public void setDeletedFlag(char deletedFlag) {
		this.deletedFlag = deletedFlag;
	}

	public char getDisabledFlag() {
		return this.disabledFlag;
	}

	public void setDisabledFlag(char disabledFlag) {
		this.disabledFlag = disabledFlag;
	}

	public char getEnableMaxSessions() {
		return this.enableMaxSessions;
	}

	public void setEnableMaxSessions(char enableMaxSessions) {
		this.enableMaxSessions = enableMaxSessions;
	}

	public char getEnableMaxCalls() {
		return this.enableMaxCalls;
	}

	public void setEnableMaxCalls(char enableMaxCalls) {
		this.enableMaxCalls = enableMaxCalls;
	}

	public Character getAllowPhoneNumberMaintenance() {
		return this.allowPhoneNumberMaintenance;
	}

	public void setAllowPhoneNumberMaintenance(
			Character allowPhoneNumberMaintenance) {
		this.allowPhoneNumberMaintenance = allowPhoneNumberMaintenance;
	}

	public Character getEnableMaxSessForParent() {
		return this.enableMaxSessForParent;
	}

	public void setEnableMaxSessForParent(Character enableMaxSessForParent) {
		this.enableMaxSessForParent = enableMaxSessForParent;
	}

	public Character getEnableMaxCallsForParent() {
		return this.enableMaxCallsForParent;
	}

	public void setEnableMaxCallsForParent(Character enableMaxCallsForParent) {
		this.enableMaxCallsForParent = enableMaxCallsForParent;
	}

	public Character getVoicemailFlag() {
		return this.voicemailFlag;
	}

	public void setVoicemailFlag(Character voicemailFlag) {
		this.voicemailFlag = voicemailFlag;
	}

	public Character getPstnEgressFlag() {
		return this.pstnEgressFlag;
	}

	public void setPstnEgressFlag(Character pstnEgressFlag) {
		this.pstnEgressFlag = pstnEgressFlag;
	}

	public String getServiceProviderCode() {
		return this.serviceProviderCode;
	}

	public void setServiceProviderCode(String serviceProviderCode) {
		this.serviceProviderCode = serviceProviderCode;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public BigDecimal getMaxSimultaneousCalls() {
		return this.maxSimultaneousCalls;
	}

	public void setMaxSimultaneousCalls(BigDecimal maxSimultaneousCalls) {
		this.maxSimultaneousCalls = maxSimultaneousCalls;
	}

	public BigDecimal getMaxCurrentCalls() {
		return this.maxCurrentCalls;
	}

	public void setMaxCurrentCalls(BigDecimal maxCurrentCalls) {
		this.maxCurrentCalls = maxCurrentCalls;
	}

	public BigDecimal getMaxSimultaneousSessions() {
		return this.maxSimultaneousSessions;
	}

	public void setMaxSimultaneousSessions(BigDecimal maxSimultaneousSessions) {
		this.maxSimultaneousSessions = maxSimultaneousSessions;
	}

	public BigDecimal getAvailableSessions() {
		return this.availableSessions;
	}

	public void setAvailableSessions(BigDecimal availableSessions) {
		this.availableSessions = availableSessions;
	}

	public BigDecimal getAvailableCalls() {
		return this.availableCalls;
	}

	public void setAvailableCalls(BigDecimal availableCalls) {
		this.availableCalls = availableCalls;
	}

	public String getEcrcNumber() {
		return this.ecrcNumber;
	}

	public void setEcrcNumber(String ecrcNumber) {
		this.ecrcNumber = ecrcNumber;
	}

	public String getForwardingNbr1() {
		return this.forwardingNbr1;
	}

	public void setForwardingNbr1(String forwardingNbr1) {
		this.forwardingNbr1 = forwardingNbr1;
	}

	public String getForwardingNbr2() {
		return this.forwardingNbr2;
	}

	public void setForwardingNbr2(String forwardingNbr2) {
		this.forwardingNbr2 = forwardingNbr2;
	}

	public String getForwardingNbr3() {
		return this.forwardingNbr3;
	}

	public void setForwardingNbr3(String forwardingNbr3) {
		this.forwardingNbr3 = forwardingNbr3;
	}

	public String getPsap1() {
		return this.psap1;
	}

	public void setPsap1(String psap1) {
		this.psap1 = psap1;
	}

	public String getPsap2() {
		return this.psap2;
	}

	public void setPsap2(String psap2) {
		this.psap2 = psap2;
	}

	public String getSipRealm() {
		return this.sipRealm;
	}

	public void setSipRealm(String sipRealm) {
		this.sipRealm = sipRealm;
	}

	public String getReportingPassword() {
		return this.reportingPassword;
	}

	public void setReportingPassword(String reportingPassword) {
		this.reportingPassword = reportingPassword;
	}

	public String getPrimarySoftswitchIp() {
		return this.primarySoftswitchIp;
	}

	public void setPrimarySoftswitchIp(String primarySoftswitchIp) {
		this.primarySoftswitchIp = primarySoftswitchIp;
	}

	public String getBackupSoftswitchIp() {
		return this.backupSoftswitchIp;
	}

	public void setBackupSoftswitchIp(String backupSoftswitchIp) {
		this.backupSoftswitchIp = backupSoftswitchIp;
	}

	public String getProxyServer() {
		return this.proxyServer;
	}

	public void setProxyServer(String proxyServer) {
		this.proxyServer = proxyServer;
	}

	public Character getCreditLimitFlag() {
		return this.creditLimitFlag;
	}

	public void setCreditLimitFlag(Character creditLimitFlag) {
		this.creditLimitFlag = creditLimitFlag;
	}

	public Character getCreditWarningMethod() {
		return this.creditWarningMethod;
	}

	public void setCreditWarningMethod(Character creditWarningMethod) {
		this.creditWarningMethod = creditWarningMethod;
	}

	public BigDecimal getCreditLimit() {
		return this.creditLimit;
	}

	public void setCreditLimit(BigDecimal creditLimit) {
		this.creditLimit = creditLimit;
	}

	public BigDecimal getCreditUsed() {
		return this.creditUsed;
	}

	public void setCreditUsed(BigDecimal creditUsed) {
		this.creditUsed = creditUsed;
	}

	public BigDecimal getCreditWarningThresholdPct() {
		return this.creditWarningThresholdPct;
	}

	public void setCreditWarningThresholdPct(
			BigDecimal creditWarningThresholdPct) {
		this.creditWarningThresholdPct = creditWarningThresholdPct;
	}

	public BigDecimal getCreditWarningThresholdAmt() {
		return this.creditWarningThresholdAmt;
	}

	public void setCreditWarningThresholdAmt(
			BigDecimal creditWarningThresholdAmt) {
		this.creditWarningThresholdAmt = creditWarningThresholdAmt;
	}

	public char getPinGenLimitFlag() {
		return this.pinGenLimitFlag;
	}

	public void setPinGenLimitFlag(char pinGenLimitFlag) {
		this.pinGenLimitFlag = pinGenLimitFlag;
	}

	public BigDecimal getPinGenLimit() {
		return this.pinGenLimit;
	}

	public void setPinGenLimit(BigDecimal pinGenLimit) {
		this.pinGenLimit = pinGenLimit;
	}

	public BigDecimal getPinGenAvailable() {
		return this.pinGenAvailable;
	}

	public void setPinGenAvailable(BigDecimal pinGenAvailable) {
		this.pinGenAvailable = pinGenAvailable;
	}

	public BigDecimal getPinGenSelfNotification() {
		return this.pinGenSelfNotification;
	}

	public void setPinGenSelfNotification(BigDecimal pinGenSelfNotification) {
		this.pinGenSelfNotification = pinGenSelfNotification;
	}

	public BigDecimal getPinGenParentNotification() {
		return this.pinGenParentNotification;
	}

	public void setPinGenParentNotification(BigDecimal pinGenParentNotification) {
		this.pinGenParentNotification = pinGenParentNotification;
	}

	public Set<SubAuthAni> getSubAuthAnis() {
		return this.subAuthAnis;
	}

	public void setSubAuthAnis(Set<SubAuthAni> subAuthAnis) {
		this.subAuthAnis = subAuthAnis;
	}

	public Set<PreActivatedSubscribers> getPreActivatedSubscriberses() {
		return this.preActivatedSubscriberses;
	}

	public void setPreActivatedSubscriberses(
			Set<PreActivatedSubscribers> preActivatedSubscriberses) {
		this.preActivatedSubscriberses = preActivatedSubscriberses;
	}

	public Set<ProductOffering> getProductOfferings() {
		return this.productOfferings;
	}

	public void setProductOfferings(Set<ProductOffering> productOfferings) {
		this.productOfferings = productOfferings;
	}

	public Set<ServiceProviderSettings> getServiceProviderSettingses() {
		return this.serviceProviderSettingses;
	}

	public void setServiceProviderSettingses(
			Set<ServiceProviderSettings> serviceProviderSettingses) {
		this.serviceProviderSettingses = serviceProviderSettingses;
	}

	public Set<AccountActivity> getAccountActivities() {
		return this.accountActivities;
	}

	public void setAccountActivities(Set<AccountActivity> accountActivities) {
		this.accountActivities = accountActivities;
	}

	public Set<AccessNumber> getAccessNumbers() {
		return this.accessNumbers;
	}

	public void setAccessNumbers(Set<AccessNumber> accessNumbers) {
		this.accessNumbers = accessNumbers;
	}

	public Set<Lot> getLots() {
		return this.lots;
	}

	public void setLots(Set<Lot> lots) {
		this.lots = lots;
	}

}
