package com.rawabi.model;

// Generated Jul 24, 2012 12:30:09 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;

/**
 * SubAuthAni generated by hbm2java
 */
public class SubAuthAni implements java.io.Serializable {

	private BigDecimal authAniId;
	private Subscriber subscriber;
	private ServiceProvider serviceProvider;
	private String phoneNumber;
	private BigDecimal pinId;

	public SubAuthAni() {
	}

	public SubAuthAni(BigDecimal authAniId, Subscriber subscriber,
			ServiceProvider serviceProvider, String phoneNumber) {
		this.authAniId = authAniId;
		this.subscriber = subscriber;
		this.serviceProvider = serviceProvider;
		this.phoneNumber = phoneNumber;
	}

	public SubAuthAni(BigDecimal authAniId, Subscriber subscriber,
			ServiceProvider serviceProvider, String phoneNumber,
			BigDecimal pinId) {
		this.authAniId = authAniId;
		this.subscriber = subscriber;
		this.serviceProvider = serviceProvider;
		this.phoneNumber = phoneNumber;
		this.pinId = pinId;
	}

	public BigDecimal getAuthAniId() {
		return this.authAniId;
	}

	public void setAuthAniId(BigDecimal authAniId) {
		this.authAniId = authAniId;
	}

	public Subscriber getSubscriber() {
		return this.subscriber;
	}

	public void setSubscriber(Subscriber subscriber) {
		this.subscriber = subscriber;
	}

	public ServiceProvider getServiceProvider() {
		return this.serviceProvider;
	}

	public void setServiceProvider(ServiceProvider serviceProvider) {
		this.serviceProvider = serviceProvider;
	}

	public String getPhoneNumber() {
		return this.phoneNumber;
	}

	public void setPhoneNumber(String phoneNumber) {
		this.phoneNumber = phoneNumber;
	}

	public BigDecimal getPinId() {
		return this.pinId;
	}

	public void setPinId(BigDecimal pinId) {
		this.pinId = pinId;
	}

}
