package com.rawabi.model;

// Generated Jul 30, 2012 10:19:37 AM by Hibernate Tools 3.4.0.CR1

/**
 * SubOfferingXref generated by hbm2java
 */
public class SubOfferingXref implements java.io.Serializable {

	private SubOfferingXrefId id;
	private Subscriber subscriber;
	private ProductOffering productOffering;
	private Character primaryFlag;

	public SubOfferingXref() {
	}

	public SubOfferingXref(SubOfferingXrefId id, Subscriber subscriber,
			ProductOffering productOffering) {
		this.id = id;
		this.subscriber = subscriber;
		this.productOffering = productOffering;
	}

	public SubOfferingXref(SubOfferingXrefId id, Subscriber subscriber,
			ProductOffering productOffering, Character primaryFlag) {
		this.id = id;
		this.subscriber = subscriber;
		this.productOffering = productOffering;
		this.primaryFlag = primaryFlag;
	}

	public SubOfferingXrefId getId() {
		return this.id;
	}

	public void setId(SubOfferingXrefId id) {
		this.id = id;
	}

	public Subscriber getSubscriber() {
		return this.subscriber;
	}

	public void setSubscriber(Subscriber subscriber) {
		this.subscriber = subscriber;
	}

	public ProductOffering getProductOffering() {
		return this.productOffering;
	}

	public void setProductOffering(ProductOffering productOffering) {
		this.productOffering = productOffering;
	}

	public Character getPrimaryFlag() {
		return this.primaryFlag;
	}

	public void setPrimaryFlag(Character primaryFlag) {
		this.primaryFlag = primaryFlag;
	}

}
