package com.rawabi.model;

// Generated Sep 19, 2012 12:44:25 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;

/**
 * SubOfferingXrefId generated by hbm2java
 */
public class SubOfferingXrefId implements java.io.Serializable {

	private BigDecimal subscriberId;
	private BigDecimal offeringId;

	public SubOfferingXrefId() {
	}

	public SubOfferingXrefId(BigDecimal subscriberId, BigDecimal offeringId) {
		this.subscriberId = subscriberId;
		this.offeringId = offeringId;
	}

	public BigDecimal getSubscriberId() {
		return this.subscriberId;
	}

	public void setSubscriberId(BigDecimal subscriberId) {
		this.subscriberId = subscriberId;
	}

	public BigDecimal getOfferingId() {
		return this.offeringId;
	}

	public void setOfferingId(BigDecimal offeringId) {
		this.offeringId = offeringId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof SubOfferingXrefId))
			return false;
		SubOfferingXrefId castOther = (SubOfferingXrefId) other;

		return ((this.getSubscriberId() == castOther.getSubscriberId()) || (this
				.getSubscriberId() != null
				&& castOther.getSubscriberId() != null && this
				.getSubscriberId().equals(castOther.getSubscriberId())))
				&& ((this.getOfferingId() == castOther.getOfferingId()) || (this
						.getOfferingId() != null
						&& castOther.getOfferingId() != null && this
						.getOfferingId().equals(castOther.getOfferingId())));
	}

	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getSubscriberId() == null ? 0 : this.getSubscriberId()
						.hashCode());
		result = 37
				* result
				+ (getOfferingId() == null ? 0 : this.getOfferingId()
						.hashCode());
		return result;
	}

}
