package com.rawabi.model;

// Generated Jul 24, 2012 12:30:09 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Subscriber generated by hbm2java
 */
public class Subscriber implements java.io.Serializable {

	private BigDecimal subscriberId;
	private CurrencyRef currencyRef;
	private ServiceProvider serviceProvider;
	private BigDecimal initialBalance;
	private BigDecimal expirationType;
	private BigDecimal languageId;
	private BigDecimal billingType;
	private BigDecimal confOperatorAssistType;
	private char disabledFlag;
	private char directCallFlag;
	private Character requireAniAuthFlag;
	private Character corpAcctMgrFlag;
	private Character allowPinOnlyLoginFlag;
	private Character callbackNbrFlag;
	private Character includeInCompanyDirFlag;
	private Date signupDate;
	private Date activationDate;
	private Date firstCallDate;
	private Date firstUseDate;
	private Date lastUseDate;
	private Date nextMaintFeeDate;
	private Date expirationDate;
	private Date zeroBalanceDate;
	private Date dateOfBirth;
	private Date lastClmResetDate;
	private Date deactivationDate;
	private Date reactivationDate;
	private BigDecimal callingSvcId;
	private BigDecimal lotId;
	private BigDecimal lotSeqNumber;
	private BigDecimal currPrepaidBalance;
	private BigDecimal primaryOfferingId;
	private String pin;
	private String loginUserId;
	private String billingId;
	private String lotControlNumber;
	private String popdAccountNumber;
	private String outboundCli;
	private String title;
	private String firstName;
	private String middleName;
	private String lastName;
	private String lastNameIndexed;
	private String nameSuffix;
	private String securityKey;
	private BigDecimal guiDisplayLanguageId;
	private BigDecimal numExpirationDays;
	private BigDecimal disabledReasonCode;
	private BigDecimal confSvcId;
	private BigDecimal corpAcctNbr;
	private BigDecimal corpDeptId;
	private BigDecimal rejectedReasonCode;
	private BigDecimal timezoneId;
	private BigDecimal homeCountryId;
	private BigDecimal creditLimit;
	private BigDecimal creditUsed;
	private BigDecimal simulCallsPerPin;
	private BigDecimal voipServiceId;
	private BigDecimal voicemailServiceId;
	private BigDecimal popdCallingSvcId;
	private String companyName;
	private String marketId;
	private String callbackNbr;
	private String prpdAccountNumber;
	private String dtmfName;
	private String loginPassword;
	private String pinPassword;
	private String orgName;
	private BigDecimal balanceNotifyThreshold;
	private Set<AccountActivity> accountActivities = new HashSet<AccountActivity>(
			0);
	private LockedPins lockedPins;
	private Set<EvtBalanceTransfer> evtBalanceTransfers = new HashSet<EvtBalanceTransfer>(
			0);
	private Set<SubAuthAni> subAuthAnis = new HashSet<SubAuthAni>(0);

	public Subscriber() {
	}

	public Subscriber(BigDecimal subscriberId, CurrencyRef currencyRef,
			ServiceProvider serviceProvider, BigDecimal initialBalance,
			BigDecimal expirationType, BigDecimal languageId,
			BigDecimal billingType, BigDecimal confOperatorAssistType,
			char disabledFlag, char directCallFlag) {
		this.subscriberId = subscriberId;
		this.currencyRef = currencyRef;
		this.serviceProvider = serviceProvider;
		this.initialBalance = initialBalance;
		this.expirationType = expirationType;
		this.languageId = languageId;
		this.billingType = billingType;
		this.confOperatorAssistType = confOperatorAssistType;
		this.disabledFlag = disabledFlag;
		this.directCallFlag = directCallFlag;
	}

	public Subscriber(BigDecimal subscriberId, CurrencyRef currencyRef,
			ServiceProvider serviceProvider, BigDecimal initialBalance,
			BigDecimal expirationType, BigDecimal languageId,
			BigDecimal billingType, BigDecimal confOperatorAssistType,
			char disabledFlag, char directCallFlag,
			Character requireAniAuthFlag, Character corpAcctMgrFlag,
			Character allowPinOnlyLoginFlag, Character callbackNbrFlag,
			Character includeInCompanyDirFlag, Date signupDate,
			Date activationDate, Date firstCallDate, Date firstUseDate,
			Date lastUseDate, Date nextMaintFeeDate, Date expirationDate,
			Date zeroBalanceDate, Date dateOfBirth, Date lastClmResetDate,
			Date deactivationDate, Date reactivationDate,
			BigDecimal callingSvcId, BigDecimal lotId, BigDecimal lotSeqNumber,
			BigDecimal currPrepaidBalance, BigDecimal primaryOfferingId,
			String pin, String loginUserId, String billingId,
			String lotControlNumber, String popdAccountNumber,
			String outboundCli, String title, String firstName,
			String middleName, String lastName, String lastNameIndexed,
			String nameSuffix, String securityKey,
			BigDecimal guiDisplayLanguageId, BigDecimal numExpirationDays,
			BigDecimal disabledReasonCode, BigDecimal confSvcId,
			BigDecimal corpAcctNbr, BigDecimal corpDeptId,
			BigDecimal rejectedReasonCode, BigDecimal timezoneId,
			BigDecimal homeCountryId, BigDecimal creditLimit,
			BigDecimal creditUsed, BigDecimal simulCallsPerPin,
			BigDecimal voipServiceId, BigDecimal voicemailServiceId,
			BigDecimal popdCallingSvcId, String companyName, String marketId,
			String callbackNbr, String prpdAccountNumber, String dtmfName,
			String loginPassword, String pinPassword, String orgName,
			BigDecimal balanceNotifyThreshold,
			Set<AccountActivity> accountActivities, LockedPins lockedPins,
			Set<EvtBalanceTransfer> evtBalanceTransfers,
			Set<SubAuthAni> subAuthAnis) {
		this.subscriberId = subscriberId;
		this.currencyRef = currencyRef;
		this.serviceProvider = serviceProvider;
		this.initialBalance = initialBalance;
		this.expirationType = expirationType;
		this.languageId = languageId;
		this.billingType = billingType;
		this.confOperatorAssistType = confOperatorAssistType;
		this.disabledFlag = disabledFlag;
		this.directCallFlag = directCallFlag;
		this.requireAniAuthFlag = requireAniAuthFlag;
		this.corpAcctMgrFlag = corpAcctMgrFlag;
		this.allowPinOnlyLoginFlag = allowPinOnlyLoginFlag;
		this.callbackNbrFlag = callbackNbrFlag;
		this.includeInCompanyDirFlag = includeInCompanyDirFlag;
		this.signupDate = signupDate;
		this.activationDate = activationDate;
		this.firstCallDate = firstCallDate;
		this.firstUseDate = firstUseDate;
		this.lastUseDate = lastUseDate;
		this.nextMaintFeeDate = nextMaintFeeDate;
		this.expirationDate = expirationDate;
		this.zeroBalanceDate = zeroBalanceDate;
		this.dateOfBirth = dateOfBirth;
		this.lastClmResetDate = lastClmResetDate;
		this.deactivationDate = deactivationDate;
		this.reactivationDate = reactivationDate;
		this.callingSvcId = callingSvcId;
		this.lotId = lotId;
		this.lotSeqNumber = lotSeqNumber;
		this.currPrepaidBalance = currPrepaidBalance;
		this.primaryOfferingId = primaryOfferingId;
		this.pin = pin;
		this.loginUserId = loginUserId;
		this.billingId = billingId;
		this.lotControlNumber = lotControlNumber;
		this.popdAccountNumber = popdAccountNumber;
		this.outboundCli = outboundCli;
		this.title = title;
		this.firstName = firstName;
		this.middleName = middleName;
		this.lastName = lastName;
		this.lastNameIndexed = lastNameIndexed;
		this.nameSuffix = nameSuffix;
		this.securityKey = securityKey;
		this.guiDisplayLanguageId = guiDisplayLanguageId;
		this.numExpirationDays = numExpirationDays;
		this.disabledReasonCode = disabledReasonCode;
		this.confSvcId = confSvcId;
		this.corpAcctNbr = corpAcctNbr;
		this.corpDeptId = corpDeptId;
		this.rejectedReasonCode = rejectedReasonCode;
		this.timezoneId = timezoneId;
		this.homeCountryId = homeCountryId;
		this.creditLimit = creditLimit;
		this.creditUsed = creditUsed;
		this.simulCallsPerPin = simulCallsPerPin;
		this.voipServiceId = voipServiceId;
		this.voicemailServiceId = voicemailServiceId;
		this.popdCallingSvcId = popdCallingSvcId;
		this.companyName = companyName;
		this.marketId = marketId;
		this.callbackNbr = callbackNbr;
		this.prpdAccountNumber = prpdAccountNumber;
		this.dtmfName = dtmfName;
		this.loginPassword = loginPassword;
		this.pinPassword = pinPassword;
		this.orgName = orgName;
		this.balanceNotifyThreshold = balanceNotifyThreshold;
		this.accountActivities = accountActivities;
		this.lockedPins = lockedPins;
		this.evtBalanceTransfers = evtBalanceTransfers;
		this.subAuthAnis = subAuthAnis;
	}

	public BigDecimal getSubscriberId() {
		return this.subscriberId;
	}

	public void setSubscriberId(BigDecimal subscriberId) {
		this.subscriberId = subscriberId;
	}

	public CurrencyRef getCurrencyRef() {
		return this.currencyRef;
	}

	public void setCurrencyRef(CurrencyRef currencyRef) {
		this.currencyRef = currencyRef;
	}

	public ServiceProvider getServiceProvider() {
		return this.serviceProvider;
	}

	public void setServiceProvider(ServiceProvider serviceProvider) {
		this.serviceProvider = serviceProvider;
	}

	public BigDecimal getInitialBalance() {
		return this.initialBalance;
	}

	public void setInitialBalance(BigDecimal initialBalance) {
		this.initialBalance = initialBalance;
	}

	public BigDecimal getExpirationType() {
		return this.expirationType;
	}

	public void setExpirationType(BigDecimal expirationType) {
		this.expirationType = expirationType;
	}

	public BigDecimal getLanguageId() {
		return this.languageId;
	}

	public void setLanguageId(BigDecimal languageId) {
		this.languageId = languageId;
	}

	public BigDecimal getBillingType() {
		return this.billingType;
	}

	public void setBillingType(BigDecimal billingType) {
		this.billingType = billingType;
	}

	public BigDecimal getConfOperatorAssistType() {
		return this.confOperatorAssistType;
	}

	public void setConfOperatorAssistType(BigDecimal confOperatorAssistType) {
		this.confOperatorAssistType = confOperatorAssistType;
	}

	public char getDisabledFlag() {
		return this.disabledFlag;
	}

	public void setDisabledFlag(char disabledFlag) {
		this.disabledFlag = disabledFlag;
	}

	public char getDirectCallFlag() {
		return this.directCallFlag;
	}

	public void setDirectCallFlag(char directCallFlag) {
		this.directCallFlag = directCallFlag;
	}

	public Character getRequireAniAuthFlag() {
		return this.requireAniAuthFlag;
	}

	public void setRequireAniAuthFlag(Character requireAniAuthFlag) {
		this.requireAniAuthFlag = requireAniAuthFlag;
	}

	public Character getCorpAcctMgrFlag() {
		return this.corpAcctMgrFlag;
	}

	public void setCorpAcctMgrFlag(Character corpAcctMgrFlag) {
		this.corpAcctMgrFlag = corpAcctMgrFlag;
	}

	public Character getAllowPinOnlyLoginFlag() {
		return this.allowPinOnlyLoginFlag;
	}

	public void setAllowPinOnlyLoginFlag(Character allowPinOnlyLoginFlag) {
		this.allowPinOnlyLoginFlag = allowPinOnlyLoginFlag;
	}

	public Character getCallbackNbrFlag() {
		return this.callbackNbrFlag;
	}

	public void setCallbackNbrFlag(Character callbackNbrFlag) {
		this.callbackNbrFlag = callbackNbrFlag;
	}

	public Character getIncludeInCompanyDirFlag() {
		return this.includeInCompanyDirFlag;
	}

	public void setIncludeInCompanyDirFlag(Character includeInCompanyDirFlag) {
		this.includeInCompanyDirFlag = includeInCompanyDirFlag;
	}

	public Date getSignupDate() {
		return this.signupDate;
	}

	public void setSignupDate(Date signupDate) {
		this.signupDate = signupDate;
	}

	public Date getActivationDate() {
		return this.activationDate;
	}

	public void setActivationDate(Date activationDate) {
		this.activationDate = activationDate;
	}

	public Date getFirstCallDate() {
		return this.firstCallDate;
	}

	public void setFirstCallDate(Date firstCallDate) {
		this.firstCallDate = firstCallDate;
	}

	public Date getFirstUseDate() {
		return this.firstUseDate;
	}

	public void setFirstUseDate(Date firstUseDate) {
		this.firstUseDate = firstUseDate;
	}

	public Date getLastUseDate() {
		return this.lastUseDate;
	}

	public void setLastUseDate(Date lastUseDate) {
		this.lastUseDate = lastUseDate;
	}

	public Date getNextMaintFeeDate() {
		return this.nextMaintFeeDate;
	}

	public void setNextMaintFeeDate(Date nextMaintFeeDate) {
		this.nextMaintFeeDate = nextMaintFeeDate;
	}

	public Date getExpirationDate() {
		return this.expirationDate;
	}

	public void setExpirationDate(Date expirationDate) {
		this.expirationDate = expirationDate;
	}

	public Date getZeroBalanceDate() {
		return this.zeroBalanceDate;
	}

	public void setZeroBalanceDate(Date zeroBalanceDate) {
		this.zeroBalanceDate = zeroBalanceDate;
	}

	public Date getDateOfBirth() {
		return this.dateOfBirth;
	}

	public void setDateOfBirth(Date dateOfBirth) {
		this.dateOfBirth = dateOfBirth;
	}

	public Date getLastClmResetDate() {
		return this.lastClmResetDate;
	}

	public void setLastClmResetDate(Date lastClmResetDate) {
		this.lastClmResetDate = lastClmResetDate;
	}

	public Date getDeactivationDate() {
		return this.deactivationDate;
	}

	public void setDeactivationDate(Date deactivationDate) {
		this.deactivationDate = deactivationDate;
	}

	public Date getReactivationDate() {
		return this.reactivationDate;
	}

	public void setReactivationDate(Date reactivationDate) {
		this.reactivationDate = reactivationDate;
	}

	public BigDecimal getCallingSvcId() {
		return this.callingSvcId;
	}

	public void setCallingSvcId(BigDecimal callingSvcId) {
		this.callingSvcId = callingSvcId;
	}

	public BigDecimal getLotId() {
		return this.lotId;
	}

	public void setLotId(BigDecimal lotId) {
		this.lotId = lotId;
	}

	public BigDecimal getLotSeqNumber() {
		return this.lotSeqNumber;
	}

	public void setLotSeqNumber(BigDecimal lotSeqNumber) {
		this.lotSeqNumber = lotSeqNumber;
	}

	public BigDecimal getCurrPrepaidBalance() {
		return this.currPrepaidBalance;
	}

	public void setCurrPrepaidBalance(BigDecimal currPrepaidBalance) {
		this.currPrepaidBalance = currPrepaidBalance;
	}

	public BigDecimal getPrimaryOfferingId() {
		return this.primaryOfferingId;
	}

	public void setPrimaryOfferingId(BigDecimal primaryOfferingId) {
		this.primaryOfferingId = primaryOfferingId;
	}

	public String getPin() {
		return this.pin;
	}

	public void setPin(String pin) {
		this.pin = pin;
	}

	public String getLoginUserId() {
		return this.loginUserId;
	}

	public void setLoginUserId(String loginUserId) {
		this.loginUserId = loginUserId;
	}

	public String getBillingId() {
		return this.billingId;
	}

	public void setBillingId(String billingId) {
		this.billingId = billingId;
	}

	public String getLotControlNumber() {
		return this.lotControlNumber;
	}

	public void setLotControlNumber(String lotControlNumber) {
		this.lotControlNumber = lotControlNumber;
	}

	public String getPopdAccountNumber() {
		return this.popdAccountNumber;
	}

	public void setPopdAccountNumber(String popdAccountNumber) {
		this.popdAccountNumber = popdAccountNumber;
	}

	public String getOutboundCli() {
		return this.outboundCli;
	}

	public void setOutboundCli(String outboundCli) {
		this.outboundCli = outboundCli;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	public String getMiddleName() {
		return this.middleName;
	}

	public void setMiddleName(String middleName) {
		this.middleName = middleName;
	}

	public String getLastName() {
		return this.lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	public String getLastNameIndexed() {
		return this.lastNameIndexed;
	}

	public void setLastNameIndexed(String lastNameIndexed) {
		this.lastNameIndexed = lastNameIndexed;
	}

	public String getNameSuffix() {
		return this.nameSuffix;
	}

	public void setNameSuffix(String nameSuffix) {
		this.nameSuffix = nameSuffix;
	}

	public String getSecurityKey() {
		return this.securityKey;
	}

	public void setSecurityKey(String securityKey) {
		this.securityKey = securityKey;
	}

	public BigDecimal getGuiDisplayLanguageId() {
		return this.guiDisplayLanguageId;
	}

	public void setGuiDisplayLanguageId(BigDecimal guiDisplayLanguageId) {
		this.guiDisplayLanguageId = guiDisplayLanguageId;
	}

	public BigDecimal getNumExpirationDays() {
		return this.numExpirationDays;
	}

	public void setNumExpirationDays(BigDecimal numExpirationDays) {
		this.numExpirationDays = numExpirationDays;
	}

	public BigDecimal getDisabledReasonCode() {
		return this.disabledReasonCode;
	}

	public void setDisabledReasonCode(BigDecimal disabledReasonCode) {
		this.disabledReasonCode = disabledReasonCode;
	}

	public BigDecimal getConfSvcId() {
		return this.confSvcId;
	}

	public void setConfSvcId(BigDecimal confSvcId) {
		this.confSvcId = confSvcId;
	}

	public BigDecimal getCorpAcctNbr() {
		return this.corpAcctNbr;
	}

	public void setCorpAcctNbr(BigDecimal corpAcctNbr) {
		this.corpAcctNbr = corpAcctNbr;
	}

	public BigDecimal getCorpDeptId() {
		return this.corpDeptId;
	}

	public void setCorpDeptId(BigDecimal corpDeptId) {
		this.corpDeptId = corpDeptId;
	}

	public BigDecimal getRejectedReasonCode() {
		return this.rejectedReasonCode;
	}

	public void setRejectedReasonCode(BigDecimal rejectedReasonCode) {
		this.rejectedReasonCode = rejectedReasonCode;
	}

	public BigDecimal getTimezoneId() {
		return this.timezoneId;
	}

	public void setTimezoneId(BigDecimal timezoneId) {
		this.timezoneId = timezoneId;
	}

	public BigDecimal getHomeCountryId() {
		return this.homeCountryId;
	}

	public void setHomeCountryId(BigDecimal homeCountryId) {
		this.homeCountryId = homeCountryId;
	}

	public BigDecimal getCreditLimit() {
		return this.creditLimit;
	}

	public void setCreditLimit(BigDecimal creditLimit) {
		this.creditLimit = creditLimit;
	}

	public BigDecimal getCreditUsed() {
		return this.creditUsed;
	}

	public void setCreditUsed(BigDecimal creditUsed) {
		this.creditUsed = creditUsed;
	}

	public BigDecimal getSimulCallsPerPin() {
		return this.simulCallsPerPin;
	}

	public void setSimulCallsPerPin(BigDecimal simulCallsPerPin) {
		this.simulCallsPerPin = simulCallsPerPin;
	}

	public BigDecimal getVoipServiceId() {
		return this.voipServiceId;
	}

	public void setVoipServiceId(BigDecimal voipServiceId) {
		this.voipServiceId = voipServiceId;
	}

	public BigDecimal getVoicemailServiceId() {
		return this.voicemailServiceId;
	}

	public void setVoicemailServiceId(BigDecimal voicemailServiceId) {
		this.voicemailServiceId = voicemailServiceId;
	}

	public BigDecimal getPopdCallingSvcId() {
		return this.popdCallingSvcId;
	}

	public void setPopdCallingSvcId(BigDecimal popdCallingSvcId) {
		this.popdCallingSvcId = popdCallingSvcId;
	}

	public String getCompanyName() {
		return this.companyName;
	}

	public void setCompanyName(String companyName) {
		this.companyName = companyName;
	}

	public String getMarketId() {
		return this.marketId;
	}

	public void setMarketId(String marketId) {
		this.marketId = marketId;
	}

	public String getCallbackNbr() {
		return this.callbackNbr;
	}

	public void setCallbackNbr(String callbackNbr) {
		this.callbackNbr = callbackNbr;
	}

	public String getPrpdAccountNumber() {
		return this.prpdAccountNumber;
	}

	public void setPrpdAccountNumber(String prpdAccountNumber) {
		this.prpdAccountNumber = prpdAccountNumber;
	}

	public String getDtmfName() {
		return this.dtmfName;
	}

	public void setDtmfName(String dtmfName) {
		this.dtmfName = dtmfName;
	}

	public String getLoginPassword() {
		return this.loginPassword;
	}

	public void setLoginPassword(String loginPassword) {
		this.loginPassword = loginPassword;
	}

	public String getPinPassword() {
		return this.pinPassword;
	}

	public void setPinPassword(String pinPassword) {
		this.pinPassword = pinPassword;
	}

	public String getOrgName() {
		return this.orgName;
	}

	public void setOrgName(String orgName) {
		this.orgName = orgName;
	}

	public BigDecimal getBalanceNotifyThreshold() {
		return this.balanceNotifyThreshold;
	}

	public void setBalanceNotifyThreshold(BigDecimal balanceNotifyThreshold) {
		this.balanceNotifyThreshold = balanceNotifyThreshold;
	}

	public Set<AccountActivity> getAccountActivities() {
		return this.accountActivities;
	}

	public void setAccountActivities(Set<AccountActivity> accountActivities) {
		this.accountActivities = accountActivities;
	}

	public LockedPins getLockedPins() {
		return this.lockedPins;
	}

	public void setLockedPins(LockedPins lockedPins) {
		this.lockedPins = lockedPins;
	}

	public Set<EvtBalanceTransfer> getEvtBalanceTransfers() {
		return this.evtBalanceTransfers;
	}

	public void setEvtBalanceTransfers(
			Set<EvtBalanceTransfer> evtBalanceTransfers) {
		this.evtBalanceTransfers = evtBalanceTransfers;
	}

	public Set<SubAuthAni> getSubAuthAnis() {
		return this.subAuthAnis;
	}

	public void setSubAuthAnis(Set<SubAuthAni> subAuthAnis) {
		this.subAuthAnis = subAuthAnis;
	}

}
