package com.rawabi.model;

// Generated Sep 19, 2012 12:44:25 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Subscriber generated by hbm2java
 */
public class Subscriber implements java.io.Serializable {

	private Long subscriberId;
	private BigDecimal offplanAlertPlayed;
	private char firstBillcyclePlayed;
	private BigDecimal onplanAlertPlayed;
	private Date nextMaintFee2Date;
	private Date nextMaintFee3Date;
	private Date nextMonthlyBillingDate;
	private BigDecimal billedSequence;
	private BigDecimal initialBalance;
	private BigDecimal serviceProviderId;
	private BigDecimal expirationType;
	private BigDecimal currencyId;
	private BigDecimal languageId;
	private BigDecimal billingType;
	private BigDecimal confOperatorAssistType;
	private char disabledFlag;
	private char directCallFlag;
	private char bucketRefillWarningFlag;
	private char bucketExhaustWarningFlag;
	private char autoPayFlag;
	private char receiveBillingEmailFlag;
	private char overrideDeptE911Address;
	private char agreedTo911TermsFlag;
	private Character requireAniAuthFlag;
	private Character corpAcctMgrFlag;
	private Character allowPinOnlyLoginFlag;
	private Character callbackNbrFlag;
	private Character includeInCompanyDirFlag;
	private Date signupDate;
	private Date activationDate;
	private Date firstCallDate;
	private Date firstUseDate;
	private Date lastUseDate;
	private Date nextMaintFeeDate;
	private Date expirationDate;
	private Date zeroBalanceDate;
	private Date dateOfBirth;
	private Date lastClmResetDate;
	private Date deactivationDate;
	private Date reactivationDate;
	private Date nextSubscriptionFeeDate;
	private BigDecimal callingSvcId;
	private BigDecimal lotId;
	private BigDecimal lotSeqNumber;
	private BigDecimal currPrepaidBalance;
	private BigDecimal primaryOfferingId;
	private BigDecimal guiDisplayLanguageId;
	private BigDecimal numExpirationDays;
	private BigDecimal disabledReasonCode;
	private BigDecimal confSvcId;
	private BigDecimal corpAcctNbr;
	private BigDecimal rejectedReasonCode;
	private BigDecimal corpDeptId;
	private BigDecimal timezoneId;
	private BigDecimal homeCountryId;
	private BigDecimal creditLimit;
	private BigDecimal creditUsed;
	private BigDecimal simulCallsPerPin;
	private BigDecimal voipServiceId;
	private BigDecimal voicemailServiceId;
	private BigDecimal popdCallingSvcId;
	private BigDecimal billingCycleDate;
	private BigDecimal secondsBalance;
	private BigDecimal secondsUsed;
	private BigDecimal dailySecondsUsed;
	private BigDecimal balanceNotifyThreshold;
	private BigDecimal creditRiskScore;
	private String title;
	private String nameSuffix;
	private String securityKey;
	private String loginUserId;
	private String pin;
	private String billingId;
	private String popdAccountNumber;
	private String firstName;
	private String middleName;
	private String marketId;
	private String dtmfName;
	private String prpdAccountNumber;
	private String lastName;
	private String lastNameIndexed;
	private String lotControlNumber;
	private String outboundCli;
	private String companyName;
	private String callbackNbr;
	private String creditRiskCompany;
	private String loginPassword;
	private String pinPassword;
	private String orgName;
	private BigDecimal firstUseFeeState;
	private Set<AccountActivity> accountActivities = new HashSet<AccountActivity>(
			0);
	private LockedPins lockedPins;
	private Set<EvtBalanceTransfer> evtBalanceTransfers = new HashSet<EvtBalanceTransfer>(
			0);
	private Set<SubOfferingXref> subOfferingXrefs = new HashSet<SubOfferingXref>(
			0);
	private Set<SubAuthAni> subAuthAnis = new HashSet<SubAuthAni>(0);

	public Subscriber() {
	}

	public Subscriber(Long subscriberId, BigDecimal offplanAlertPlayed,
			char firstBillcyclePlayed, BigDecimal onplanAlertPlayed,
			BigDecimal billedSequence, BigDecimal initialBalance,
			BigDecimal serviceProviderId, BigDecimal expirationType,
			BigDecimal currencyId, BigDecimal languageId,
			BigDecimal billingType, BigDecimal confOperatorAssistType,
			char disabledFlag, char directCallFlag,
			char bucketRefillWarningFlag, char bucketExhaustWarningFlag,
			char autoPayFlag, char receiveBillingEmailFlag,
			char overrideDeptE911Address, char agreedTo911TermsFlag,
			BigDecimal firstUseFeeState) {
		this.subscriberId = subscriberId;
		this.offplanAlertPlayed = offplanAlertPlayed;
		this.firstBillcyclePlayed = firstBillcyclePlayed;
		this.onplanAlertPlayed = onplanAlertPlayed;
		this.billedSequence = billedSequence;
		this.initialBalance = initialBalance;
		this.serviceProviderId = serviceProviderId;
		this.expirationType = expirationType;
		this.currencyId = currencyId;
		this.languageId = languageId;
		this.billingType = billingType;
		this.confOperatorAssistType = confOperatorAssistType;
		this.disabledFlag = disabledFlag;
		this.directCallFlag = directCallFlag;
		this.bucketRefillWarningFlag = bucketRefillWarningFlag;
		this.bucketExhaustWarningFlag = bucketExhaustWarningFlag;
		this.autoPayFlag = autoPayFlag;
		this.receiveBillingEmailFlag = receiveBillingEmailFlag;
		this.overrideDeptE911Address = overrideDeptE911Address;
		this.agreedTo911TermsFlag = agreedTo911TermsFlag;
		this.firstUseFeeState = firstUseFeeState;
	}

	public Subscriber(Long subscriberId, BigDecimal offplanAlertPlayed,
			char firstBillcyclePlayed, BigDecimal onplanAlertPlayed,
			Date nextMaintFee2Date, Date nextMaintFee3Date,
			Date nextMonthlyBillingDate, BigDecimal billedSequence,
			BigDecimal initialBalance, BigDecimal serviceProviderId,
			BigDecimal expirationType, BigDecimal currencyId,
			BigDecimal languageId, BigDecimal billingType,
			BigDecimal confOperatorAssistType, char disabledFlag,
			char directCallFlag, char bucketRefillWarningFlag,
			char bucketExhaustWarningFlag, char autoPayFlag,
			char receiveBillingEmailFlag, char overrideDeptE911Address,
			char agreedTo911TermsFlag, Character requireAniAuthFlag,
			Character corpAcctMgrFlag, Character allowPinOnlyLoginFlag,
			Character callbackNbrFlag, Character includeInCompanyDirFlag,
			Date signupDate, Date activationDate, Date firstCallDate,
			Date firstUseDate, Date lastUseDate, Date nextMaintFeeDate,
			Date expirationDate, Date zeroBalanceDate, Date dateOfBirth,
			Date lastClmResetDate, Date deactivationDate,
			Date reactivationDate, Date nextSubscriptionFeeDate,
			BigDecimal callingSvcId, BigDecimal lotId, BigDecimal lotSeqNumber,
			BigDecimal currPrepaidBalance, BigDecimal primaryOfferingId,
			BigDecimal guiDisplayLanguageId, BigDecimal numExpirationDays,
			BigDecimal disabledReasonCode, BigDecimal confSvcId,
			BigDecimal corpAcctNbr, BigDecimal rejectedReasonCode,
			BigDecimal corpDeptId, BigDecimal timezoneId,
			BigDecimal homeCountryId, BigDecimal creditLimit,
			BigDecimal creditUsed, BigDecimal simulCallsPerPin,
			BigDecimal voipServiceId, BigDecimal voicemailServiceId,
			BigDecimal popdCallingSvcId, BigDecimal billingCycleDate,
			BigDecimal secondsBalance, BigDecimal secondsUsed,
			BigDecimal dailySecondsUsed, BigDecimal balanceNotifyThreshold,
			BigDecimal creditRiskScore, String title, String nameSuffix,
			String securityKey, String loginUserId, String pin,
			String billingId, String popdAccountNumber, String firstName,
			String middleName, String marketId, String dtmfName,
			String prpdAccountNumber, String lastName, String lastNameIndexed,
			String lotControlNumber, String outboundCli, String companyName,
			String callbackNbr, String creditRiskCompany, String loginPassword,
			String pinPassword, String orgName, BigDecimal firstUseFeeState,
			Set<AccountActivity> accountActivities, LockedPins lockedPins,
			Set<EvtBalanceTransfer> evtBalanceTransfers,
			Set<SubOfferingXref> subOfferingXrefs, Set<SubAuthAni> subAuthAnis) {
		this.subscriberId = subscriberId;
		this.offplanAlertPlayed = offplanAlertPlayed;
		this.firstBillcyclePlayed = firstBillcyclePlayed;
		this.onplanAlertPlayed = onplanAlertPlayed;
		this.nextMaintFee2Date = nextMaintFee2Date;
		this.nextMaintFee3Date = nextMaintFee3Date;
		this.nextMonthlyBillingDate = nextMonthlyBillingDate;
		this.billedSequence = billedSequence;
		this.initialBalance = initialBalance;
		this.serviceProviderId = serviceProviderId;
		this.expirationType = expirationType;
		this.currencyId = currencyId;
		this.languageId = languageId;
		this.billingType = billingType;
		this.confOperatorAssistType = confOperatorAssistType;
		this.disabledFlag = disabledFlag;
		this.directCallFlag = directCallFlag;
		this.bucketRefillWarningFlag = bucketRefillWarningFlag;
		this.bucketExhaustWarningFlag = bucketExhaustWarningFlag;
		this.autoPayFlag = autoPayFlag;
		this.receiveBillingEmailFlag = receiveBillingEmailFlag;
		this.overrideDeptE911Address = overrideDeptE911Address;
		this.agreedTo911TermsFlag = agreedTo911TermsFlag;
		this.requireAniAuthFlag = requireAniAuthFlag;
		this.corpAcctMgrFlag = corpAcctMgrFlag;
		this.allowPinOnlyLoginFlag = allowPinOnlyLoginFlag;
		this.callbackNbrFlag = callbackNbrFlag;
		this.includeInCompanyDirFlag = includeInCompanyDirFlag;
		this.signupDate = signupDate;
		this.activationDate = activationDate;
		this.firstCallDate = firstCallDate;
		this.firstUseDate = firstUseDate;
		this.lastUseDate = lastUseDate;
		this.nextMaintFeeDate = nextMaintFeeDate;
		this.expirationDate = expirationDate;
		this.zeroBalanceDate = zeroBalanceDate;
		this.dateOfBirth = dateOfBirth;
		this.lastClmResetDate = lastClmResetDate;
		this.deactivationDate = deactivationDate;
		this.reactivationDate = reactivationDate;
		this.nextSubscriptionFeeDate = nextSubscriptionFeeDate;
		this.callingSvcId = callingSvcId;
		this.lotId = lotId;
		this.lotSeqNumber = lotSeqNumber;
		this.currPrepaidBalance = currPrepaidBalance;
		this.primaryOfferingId = primaryOfferingId;
		this.guiDisplayLanguageId = guiDisplayLanguageId;
		this.numExpirationDays = numExpirationDays;
		this.disabledReasonCode = disabledReasonCode;
		this.confSvcId = confSvcId;
		this.corpAcctNbr = corpAcctNbr;
		this.rejectedReasonCode = rejectedReasonCode;
		this.corpDeptId = corpDeptId;
		this.timezoneId = timezoneId;
		this.homeCountryId = homeCountryId;
		this.creditLimit = creditLimit;
		this.creditUsed = creditUsed;
		this.simulCallsPerPin = simulCallsPerPin;
		this.voipServiceId = voipServiceId;
		this.voicemailServiceId = voicemailServiceId;
		this.popdCallingSvcId = popdCallingSvcId;
		this.billingCycleDate = billingCycleDate;
		this.secondsBalance = secondsBalance;
		this.secondsUsed = secondsUsed;
		this.dailySecondsUsed = dailySecondsUsed;
		this.balanceNotifyThreshold = balanceNotifyThreshold;
		this.creditRiskScore = creditRiskScore;
		this.title = title;
		this.nameSuffix = nameSuffix;
		this.securityKey = securityKey;
		this.loginUserId = loginUserId;
		this.pin = pin;
		this.billingId = billingId;
		this.popdAccountNumber = popdAccountNumber;
		this.firstName = firstName;
		this.middleName = middleName;
		this.marketId = marketId;
		this.dtmfName = dtmfName;
		this.prpdAccountNumber = prpdAccountNumber;
		this.lastName = lastName;
		this.lastNameIndexed = lastNameIndexed;
		this.lotControlNumber = lotControlNumber;
		this.outboundCli = outboundCli;
		this.companyName = companyName;
		this.callbackNbr = callbackNbr;
		this.creditRiskCompany = creditRiskCompany;
		this.loginPassword = loginPassword;
		this.pinPassword = pinPassword;
		this.orgName = orgName;
		this.firstUseFeeState = firstUseFeeState;
		this.accountActivities = accountActivities;
		this.lockedPins = lockedPins;
		this.evtBalanceTransfers = evtBalanceTransfers;
		this.subOfferingXrefs = subOfferingXrefs;
		this.subAuthAnis = subAuthAnis;
	}

	public Long getSubscriberId() {
		return this.subscriberId;
	}

	public void setSubscriberId(Long subscriberId) {
		this.subscriberId = subscriberId;
	}

	public BigDecimal getOffplanAlertPlayed() {
		return this.offplanAlertPlayed;
	}

	public void setOffplanAlertPlayed(BigDecimal offplanAlertPlayed) {
		this.offplanAlertPlayed = offplanAlertPlayed;
	}

	public char getFirstBillcyclePlayed() {
		return this.firstBillcyclePlayed;
	}

	public void setFirstBillcyclePlayed(char firstBillcyclePlayed) {
		this.firstBillcyclePlayed = firstBillcyclePlayed;
	}

	public BigDecimal getOnplanAlertPlayed() {
		return this.onplanAlertPlayed;
	}

	public void setOnplanAlertPlayed(BigDecimal onplanAlertPlayed) {
		this.onplanAlertPlayed = onplanAlertPlayed;
	}

	public Date getNextMaintFee2Date() {
		return this.nextMaintFee2Date;
	}

	public void setNextMaintFee2Date(Date nextMaintFee2Date) {
		this.nextMaintFee2Date = nextMaintFee2Date;
	}

	public Date getNextMaintFee3Date() {
		return this.nextMaintFee3Date;
	}

	public void setNextMaintFee3Date(Date nextMaintFee3Date) {
		this.nextMaintFee3Date = nextMaintFee3Date;
	}

	public Date getNextMonthlyBillingDate() {
		return this.nextMonthlyBillingDate;
	}

	public void setNextMonthlyBillingDate(Date nextMonthlyBillingDate) {
		this.nextMonthlyBillingDate = nextMonthlyBillingDate;
	}

	public BigDecimal getBilledSequence() {
		return this.billedSequence;
	}

	public void setBilledSequence(BigDecimal billedSequence) {
		this.billedSequence = billedSequence;
	}

	public BigDecimal getInitialBalance() {
		return this.initialBalance;
	}

	public void setInitialBalance(BigDecimal initialBalance) {
		this.initialBalance = initialBalance;
	}

	public BigDecimal getServiceProviderId() {
		return this.serviceProviderId;
	}

	public void setServiceProviderId(BigDecimal serviceProviderId) {
		this.serviceProviderId = serviceProviderId;
	}

	public BigDecimal getExpirationType() {
		return this.expirationType;
	}

	public void setExpirationType(BigDecimal expirationType) {
		this.expirationType = expirationType;
	}

	public BigDecimal getCurrencyId() {
		return this.currencyId;
	}

	public void setCurrencyId(BigDecimal currencyId) {
		this.currencyId = currencyId;
	}

	public BigDecimal getLanguageId() {
		return this.languageId;
	}

	public void setLanguageId(BigDecimal languageId) {
		this.languageId = languageId;
	}

	public BigDecimal getBillingType() {
		return this.billingType;
	}

	public void setBillingType(BigDecimal billingType) {
		this.billingType = billingType;
	}

	public BigDecimal getConfOperatorAssistType() {
		return this.confOperatorAssistType;
	}

	public void setConfOperatorAssistType(BigDecimal confOperatorAssistType) {
		this.confOperatorAssistType = confOperatorAssistType;
	}

	public char getDisabledFlag() {
		return this.disabledFlag;
	}

	public void setDisabledFlag(char disabledFlag) {
		this.disabledFlag = disabledFlag;
	}

	public char getDirectCallFlag() {
		return this.directCallFlag;
	}

	public void setDirectCallFlag(char directCallFlag) {
		this.directCallFlag = directCallFlag;
	}

	public char getBucketRefillWarningFlag() {
		return this.bucketRefillWarningFlag;
	}

	public void setBucketRefillWarningFlag(char bucketRefillWarningFlag) {
		this.bucketRefillWarningFlag = bucketRefillWarningFlag;
	}

	public char getBucketExhaustWarningFlag() {
		return this.bucketExhaustWarningFlag;
	}

	public void setBucketExhaustWarningFlag(char bucketExhaustWarningFlag) {
		this.bucketExhaustWarningFlag = bucketExhaustWarningFlag;
	}

	public char getAutoPayFlag() {
		return this.autoPayFlag;
	}

	public void setAutoPayFlag(char autoPayFlag) {
		this.autoPayFlag = autoPayFlag;
	}

	public char getReceiveBillingEmailFlag() {
		return this.receiveBillingEmailFlag;
	}

	public void setReceiveBillingEmailFlag(char receiveBillingEmailFlag) {
		this.receiveBillingEmailFlag = receiveBillingEmailFlag;
	}

	public char getOverrideDeptE911Address() {
		return this.overrideDeptE911Address;
	}

	public void setOverrideDeptE911Address(char overrideDeptE911Address) {
		this.overrideDeptE911Address = overrideDeptE911Address;
	}

	public char getAgreedTo911TermsFlag() {
		return this.agreedTo911TermsFlag;
	}

	public void setAgreedTo911TermsFlag(char agreedTo911TermsFlag) {
		this.agreedTo911TermsFlag = agreedTo911TermsFlag;
	}

	public Character getRequireAniAuthFlag() {
		return this.requireAniAuthFlag;
	}

	public void setRequireAniAuthFlag(Character requireAniAuthFlag) {
		this.requireAniAuthFlag = requireAniAuthFlag;
	}

	public Character getCorpAcctMgrFlag() {
		return this.corpAcctMgrFlag;
	}

	public void setCorpAcctMgrFlag(Character corpAcctMgrFlag) {
		this.corpAcctMgrFlag = corpAcctMgrFlag;
	}

	public Character getAllowPinOnlyLoginFlag() {
		return this.allowPinOnlyLoginFlag;
	}

	public void setAllowPinOnlyLoginFlag(Character allowPinOnlyLoginFlag) {
		this.allowPinOnlyLoginFlag = allowPinOnlyLoginFlag;
	}

	public Character getCallbackNbrFlag() {
		return this.callbackNbrFlag;
	}

	public void setCallbackNbrFlag(Character callbackNbrFlag) {
		this.callbackNbrFlag = callbackNbrFlag;
	}

	public Character getIncludeInCompanyDirFlag() {
		return this.includeInCompanyDirFlag;
	}

	public void setIncludeInCompanyDirFlag(Character includeInCompanyDirFlag) {
		this.includeInCompanyDirFlag = includeInCompanyDirFlag;
	}

	public Date getSignupDate() {
		return this.signupDate;
	}

	public void setSignupDate(Date signupDate) {
		this.signupDate = signupDate;
	}

	public Date getActivationDate() {
		return this.activationDate;
	}

	public void setActivationDate(Date activationDate) {
		this.activationDate = activationDate;
	}

	public Date getFirstCallDate() {
		return this.firstCallDate;
	}

	public void setFirstCallDate(Date firstCallDate) {
		this.firstCallDate = firstCallDate;
	}

	public Date getFirstUseDate() {
		return this.firstUseDate;
	}

	public void setFirstUseDate(Date firstUseDate) {
		this.firstUseDate = firstUseDate;
	}

	public Date getLastUseDate() {
		return this.lastUseDate;
	}

	public void setLastUseDate(Date lastUseDate) {
		this.lastUseDate = lastUseDate;
	}

	public Date getNextMaintFeeDate() {
		return this.nextMaintFeeDate;
	}

	public void setNextMaintFeeDate(Date nextMaintFeeDate) {
		this.nextMaintFeeDate = nextMaintFeeDate;
	}

	public Date getExpirationDate() {
		return this.expirationDate;
	}

	public void setExpirationDate(Date expirationDate) {
		this.expirationDate = expirationDate;
	}

	public Date getZeroBalanceDate() {
		return this.zeroBalanceDate;
	}

	public void setZeroBalanceDate(Date zeroBalanceDate) {
		this.zeroBalanceDate = zeroBalanceDate;
	}

	public Date getDateOfBirth() {
		return this.dateOfBirth;
	}

	public void setDateOfBirth(Date dateOfBirth) {
		this.dateOfBirth = dateOfBirth;
	}

	public Date getLastClmResetDate() {
		return this.lastClmResetDate;
	}

	public void setLastClmResetDate(Date lastClmResetDate) {
		this.lastClmResetDate = lastClmResetDate;
	}

	public Date getDeactivationDate() {
		return this.deactivationDate;
	}

	public void setDeactivationDate(Date deactivationDate) {
		this.deactivationDate = deactivationDate;
	}

	public Date getReactivationDate() {
		return this.reactivationDate;
	}

	public void setReactivationDate(Date reactivationDate) {
		this.reactivationDate = reactivationDate;
	}

	public Date getNextSubscriptionFeeDate() {
		return this.nextSubscriptionFeeDate;
	}

	public void setNextSubscriptionFeeDate(Date nextSubscriptionFeeDate) {
		this.nextSubscriptionFeeDate = nextSubscriptionFeeDate;
	}

	public BigDecimal getCallingSvcId() {
		return this.callingSvcId;
	}

	public void setCallingSvcId(BigDecimal callingSvcId) {
		this.callingSvcId = callingSvcId;
	}

	public BigDecimal getLotId() {
		return this.lotId;
	}

	public void setLotId(BigDecimal lotId) {
		this.lotId = lotId;
	}

	public BigDecimal getLotSeqNumber() {
		return this.lotSeqNumber;
	}

	public void setLotSeqNumber(BigDecimal lotSeqNumber) {
		this.lotSeqNumber = lotSeqNumber;
	}

	public BigDecimal getCurrPrepaidBalance() {
		return this.currPrepaidBalance;
	}

	public void setCurrPrepaidBalance(BigDecimal currPrepaidBalance) {
		this.currPrepaidBalance = currPrepaidBalance;
	}

	public BigDecimal getPrimaryOfferingId() {
		return this.primaryOfferingId;
	}

	public void setPrimaryOfferingId(BigDecimal primaryOfferingId) {
		this.primaryOfferingId = primaryOfferingId;
	}

	public BigDecimal getGuiDisplayLanguageId() {
		return this.guiDisplayLanguageId;
	}

	public void setGuiDisplayLanguageId(BigDecimal guiDisplayLanguageId) {
		this.guiDisplayLanguageId = guiDisplayLanguageId;
	}

	public BigDecimal getNumExpirationDays() {
		return this.numExpirationDays;
	}

	public void setNumExpirationDays(BigDecimal numExpirationDays) {
		this.numExpirationDays = numExpirationDays;
	}

	public BigDecimal getDisabledReasonCode() {
		return this.disabledReasonCode;
	}

	public void setDisabledReasonCode(BigDecimal disabledReasonCode) {
		this.disabledReasonCode = disabledReasonCode;
	}

	public BigDecimal getConfSvcId() {
		return this.confSvcId;
	}

	public void setConfSvcId(BigDecimal confSvcId) {
		this.confSvcId = confSvcId;
	}

	public BigDecimal getCorpAcctNbr() {
		return this.corpAcctNbr;
	}

	public void setCorpAcctNbr(BigDecimal corpAcctNbr) {
		this.corpAcctNbr = corpAcctNbr;
	}

	public BigDecimal getRejectedReasonCode() {
		return this.rejectedReasonCode;
	}

	public void setRejectedReasonCode(BigDecimal rejectedReasonCode) {
		this.rejectedReasonCode = rejectedReasonCode;
	}

	public BigDecimal getCorpDeptId() {
		return this.corpDeptId;
	}

	public void setCorpDeptId(BigDecimal corpDeptId) {
		this.corpDeptId = corpDeptId;
	}

	public BigDecimal getTimezoneId() {
		return this.timezoneId;
	}

	public void setTimezoneId(BigDecimal timezoneId) {
		this.timezoneId = timezoneId;
	}

	public BigDecimal getHomeCountryId() {
		return this.homeCountryId;
	}

	public void setHomeCountryId(BigDecimal homeCountryId) {
		this.homeCountryId = homeCountryId;
	}

	public BigDecimal getCreditLimit() {
		return this.creditLimit;
	}

	public void setCreditLimit(BigDecimal creditLimit) {
		this.creditLimit = creditLimit;
	}

	public BigDecimal getCreditUsed() {
		return this.creditUsed;
	}

	public void setCreditUsed(BigDecimal creditUsed) {
		this.creditUsed = creditUsed;
	}

	public BigDecimal getSimulCallsPerPin() {
		return this.simulCallsPerPin;
	}

	public void setSimulCallsPerPin(BigDecimal simulCallsPerPin) {
		this.simulCallsPerPin = simulCallsPerPin;
	}

	public BigDecimal getVoipServiceId() {
		return this.voipServiceId;
	}

	public void setVoipServiceId(BigDecimal voipServiceId) {
		this.voipServiceId = voipServiceId;
	}

	public BigDecimal getVoicemailServiceId() {
		return this.voicemailServiceId;
	}

	public void setVoicemailServiceId(BigDecimal voicemailServiceId) {
		this.voicemailServiceId = voicemailServiceId;
	}

	public BigDecimal getPopdCallingSvcId() {
		return this.popdCallingSvcId;
	}

	public void setPopdCallingSvcId(BigDecimal popdCallingSvcId) {
		this.popdCallingSvcId = popdCallingSvcId;
	}

	public BigDecimal getBillingCycleDate() {
		return this.billingCycleDate;
	}

	public void setBillingCycleDate(BigDecimal billingCycleDate) {
		this.billingCycleDate = billingCycleDate;
	}

	public BigDecimal getSecondsBalance() {
		return this.secondsBalance;
	}

	public void setSecondsBalance(BigDecimal secondsBalance) {
		this.secondsBalance = secondsBalance;
	}

	public BigDecimal getSecondsUsed() {
		return this.secondsUsed;
	}

	public void setSecondsUsed(BigDecimal secondsUsed) {
		this.secondsUsed = secondsUsed;
	}

	public BigDecimal getDailySecondsUsed() {
		return this.dailySecondsUsed;
	}

	public void setDailySecondsUsed(BigDecimal dailySecondsUsed) {
		this.dailySecondsUsed = dailySecondsUsed;
	}

	public BigDecimal getBalanceNotifyThreshold() {
		return this.balanceNotifyThreshold;
	}

	public void setBalanceNotifyThreshold(BigDecimal balanceNotifyThreshold) {
		this.balanceNotifyThreshold = balanceNotifyThreshold;
	}

	public BigDecimal getCreditRiskScore() {
		return this.creditRiskScore;
	}

	public void setCreditRiskScore(BigDecimal creditRiskScore) {
		this.creditRiskScore = creditRiskScore;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public String getNameSuffix() {
		return this.nameSuffix;
	}

	public void setNameSuffix(String nameSuffix) {
		this.nameSuffix = nameSuffix;
	}

	public String getSecurityKey() {
		return this.securityKey;
	}

	public void setSecurityKey(String securityKey) {
		this.securityKey = securityKey;
	}

	public String getLoginUserId() {
		return this.loginUserId;
	}

	public void setLoginUserId(String loginUserId) {
		this.loginUserId = loginUserId;
	}

	public String getPin() {
		return this.pin;
	}

	public void setPin(String pin) {
		this.pin = pin;
	}

	public String getBillingId() {
		return this.billingId;
	}

	public void setBillingId(String billingId) {
		this.billingId = billingId;
	}

	public String getPopdAccountNumber() {
		return this.popdAccountNumber;
	}

	public void setPopdAccountNumber(String popdAccountNumber) {
		this.popdAccountNumber = popdAccountNumber;
	}

	public String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	public String getMiddleName() {
		return this.middleName;
	}

	public void setMiddleName(String middleName) {
		this.middleName = middleName;
	}

	public String getMarketId() {
		return this.marketId;
	}

	public void setMarketId(String marketId) {
		this.marketId = marketId;
	}

	public String getDtmfName() {
		return this.dtmfName;
	}

	public void setDtmfName(String dtmfName) {
		this.dtmfName = dtmfName;
	}

	public String getPrpdAccountNumber() {
		return this.prpdAccountNumber;
	}

	public void setPrpdAccountNumber(String prpdAccountNumber) {
		this.prpdAccountNumber = prpdAccountNumber;
	}

	public String getLastName() {
		return this.lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	public String getLastNameIndexed() {
		return this.lastNameIndexed;
	}

	public void setLastNameIndexed(String lastNameIndexed) {
		this.lastNameIndexed = lastNameIndexed;
	}

	public String getLotControlNumber() {
		return this.lotControlNumber;
	}

	public void setLotControlNumber(String lotControlNumber) {
		this.lotControlNumber = lotControlNumber;
	}

	public String getOutboundCli() {
		return this.outboundCli;
	}

	public void setOutboundCli(String outboundCli) {
		this.outboundCli = outboundCli;
	}

	public String getCompanyName() {
		return this.companyName;
	}

	public void setCompanyName(String companyName) {
		this.companyName = companyName;
	}

	public String getCallbackNbr() {
		return this.callbackNbr;
	}

	public void setCallbackNbr(String callbackNbr) {
		this.callbackNbr = callbackNbr;
	}

	public String getCreditRiskCompany() {
		return this.creditRiskCompany;
	}

	public void setCreditRiskCompany(String creditRiskCompany) {
		this.creditRiskCompany = creditRiskCompany;
	}

	public String getLoginPassword() {
		return this.loginPassword;
	}

	public void setLoginPassword(String loginPassword) {
		this.loginPassword = loginPassword;
	}

	public String getPinPassword() {
		return this.pinPassword;
	}

	public void setPinPassword(String pinPassword) {
		this.pinPassword = pinPassword;
	}

	public String getOrgName() {
		return this.orgName;
	}

	public void setOrgName(String orgName) {
		this.orgName = orgName;
	}

	public BigDecimal getFirstUseFeeState() {
		return this.firstUseFeeState;
	}

	public void setFirstUseFeeState(BigDecimal firstUseFeeState) {
		this.firstUseFeeState = firstUseFeeState;
	}

	public Set<AccountActivity> getAccountActivities() {
		return this.accountActivities;
	}

	public void setAccountActivities(Set<AccountActivity> accountActivities) {
		this.accountActivities = accountActivities;
	}

	public LockedPins getLockedPins() {
		return this.lockedPins;
	}

	public void setLockedPins(LockedPins lockedPins) {
		this.lockedPins = lockedPins;
	}

	public Set<EvtBalanceTransfer> getEvtBalanceTransfers() {
		return this.evtBalanceTransfers;
	}

	public void setEvtBalanceTransfers(
			Set<EvtBalanceTransfer> evtBalanceTransfers) {
		this.evtBalanceTransfers = evtBalanceTransfers;
	}

	public Set<SubOfferingXref> getSubOfferingXrefs() {
		return this.subOfferingXrefs;
	}

	public void setSubOfferingXrefs(Set<SubOfferingXref> subOfferingXrefs) {
		this.subOfferingXrefs = subOfferingXrefs;
	}

	public Set<SubAuthAni> getSubAuthAnis() {
		return this.subAuthAnis;
	}

	public void setSubAuthAnis(Set<SubAuthAni> subAuthAnis) {
		this.subAuthAnis = subAuthAnis;
	}

}
